# Generated by Django 5.2.13 on 2026-04-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_external_sync_log'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cloudaccountconfig',
            table='core_cloud_account',
        ),
        migrations.AlterModelTable(
            name='externalsynclog',
            table='core_sync_log',
        ),
        migrations.AlterModelTable(
            name='siteconfig',
            table='core_site_config',
        ),
    ]
