# Generated by OpenClaw

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cloudaccount_external_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='排序'),
        ),
    ]
