# Generated by Django 5.2.13 on 2026-06-03 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_port_override_texts'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='cloudaccountconfig',
            table_comment='云厂商和外部服务账号配置表',
        ),
        migrations.AlterModelTableComment(
            name='externalsynclog',
            table_comment='外部系统同步调用日志表',
        ),
        migrations.AlterModelTableComment(
            name='siteconfig',
            table_comment='系统运行配置表',
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='access_key',
            field=models.TextField(db_comment='加密存储的云账号访问密钥', verbose_name='Access Key'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='external_account_id',
            field=models.CharField(blank=True, db_comment='云厂商账号ID', db_index=True, max_length=128, null=True, verbose_name='云厂商账号ID'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='is_active',
            field=models.BooleanField(db_comment='启用', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, db_comment='最近巡检时间', null=True, verbose_name='最近巡检时间'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='name',
            field=models.CharField(db_comment='账户名称', max_length=128, verbose_name='账户名称'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='provider',
            field=models.CharField(choices=[('aws', 'AWS'), ('aliyun', '阿里云'), ('trongrid', 'TRONGrid')], db_comment='云厂商', db_index=True, max_length=32, verbose_name='云厂商'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='region_hint',
            field=models.CharField(blank=True, db_comment='默认地区', max_length=128, null=True, verbose_name='默认地区'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='secret_key',
            field=models.TextField(db_comment='加密存储的云账号私密密钥', verbose_name='Secret Key'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='shutdown_enabled',
            field=models.BooleanField(db_comment='关机计划启用', db_index=True, default=True, verbose_name='关机计划启用'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='status',
            field=models.CharField(choices=[('unknown', '未检查'), ('ok', '正常'), ('error', '异常'), ('unsupported', '暂不支持')], db_comment='巡检状态', db_index=True, default='unknown', max_length=32, verbose_name='巡检状态'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='status_note',
            field=models.TextField(blank=True, db_comment='巡检说明', null=True, verbose_name='巡检说明'),
        ),
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='account',
            field=models.ForeignKey(blank=True, db_comment='关联账户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='core.cloudaccountconfig', verbose_name='关联账户'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='action',
            field=models.CharField(db_comment='动作', db_index=True, max_length=64, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='error_message',
            field=models.TextField(blank=True, db_comment='错误信息', null=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='is_success',
            field=models.BooleanField(db_comment='是否成功', db_index=True, default=True, verbose_name='是否成功'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='request_payload',
            field=models.TextField(blank=True, db_comment='请求载荷', null=True, verbose_name='请求载荷'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='response_payload',
            field=models.TextField(blank=True, db_comment='响应载荷', null=True, verbose_name='响应载荷'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='source',
            field=models.CharField(choices=[('trongrid', 'TRONGrid'), ('aws_lightsail', 'AWS Lightsail'), ('aliyun', '阿里云'), ('dashboard', '后台接口')], db_comment='来源', db_index=True, max_length=32, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='target',
            field=models.CharField(blank=True, db_comment='目标', db_index=True, max_length=191, null=True, verbose_name='目标'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='is_sensitive',
            field=models.BooleanField(db_comment='是否按敏感配置加密存储', default=False, verbose_name='敏感配置'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='key',
            field=models.CharField(db_comment='键', db_index=True, max_length=191, unique=True, verbose_name='键'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='sort_order',
            field=models.IntegerField(db_comment='排序', db_index=True, default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='value',
            field=models.TextField(blank=True, db_comment='配置值；敏感配置会加密存储', null=True, verbose_name='值'),
        ),
    ]
