# Generated by Django 5.2.13 on 2026-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cloudaccountconfig_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudaccountconfig',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalsynclog',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
