from django.urls import path

from bot import api as bot_api
from cloud import api_asset_edit as cloud_asset_edit_api
from cloud import api_assets as cloud_asset_api
from cloud import api_monitors as cloud_monitor_api
from cloud import api_orders as cloud_order_api
from cloud import api_plans as cloud_plan_api
from cloud import api_servers as cloud_server_api
from cloud import api_sync as cloud_sync_api
from cloud import api_tasks as cloud_task_api
from cloud import sync_jobs as cloud_sync_jobs
from cloud import task_center as cloud_task_center
from orders import api as orders_api

app_name = 'admin_api'

urlpatterns = [
    path('auth/totp/start', bot_api.auth_totp_start, name='auth-totp-start'),
    path('auth/totp/bind', bot_api.auth_totp_bind, name='auth-totp-bind'),
    path('user/info', bot_api.user_info, name='user-info'),
    path('dashboard/me/', bot_api.me, name='me'),
    path('dashboard/overview/', bot_api.overview, name='overview'),
    path('dashboard/ip-delete-logs/', bot_api.ip_delete_logs, name='ip-delete-logs'),
    path('users/', bot_api.users_list, name='users-list'),
    path('users/<int:user_id>/balance/', bot_api.update_user_balance, name='user-balance-update'),
    path('users/<int:user_id>/discount/', bot_api.update_user_discount, name='user-discount-update'),
    path('users/<int:user_id>/balance-details/', bot_api.user_balance_details, name='user-balance-details'),
    path('telegram/accounts/', bot_api.telegram_accounts_overview, name='telegram-accounts-overview'),
    path('telegram/accounts/create/', bot_api.create_telegram_login_account, name='telegram-account-create'),
    path('telegram/accounts/<int:account_id>/status/', bot_api.check_telegram_login_account_status, name='telegram-account-status-check'),
    path('telegram/accounts/<int:account_id>/notify/', bot_api.update_telegram_account_notify, name='telegram-account-notify'),
    path('telegram/login/start/', bot_api.telegram_login_start, name='telegram-login-start'),
    path('telegram/login/code/', bot_api.telegram_login_code, name='telegram-login-code'),
    path('telegram/login/password/', bot_api.telegram_login_password, name='telegram-login-password'),
    path('telegram/chats/archive/', bot_api.archive_telegram_chat, name='telegram-chat-archive'),
    path('telegram/groups/', bot_api.telegram_group_filters_list, name='telegram-groups-list'),
    path('telegram/groups/create/', bot_api.create_telegram_group_filter, name='telegram-group-create'),
    path('telegram/groups/<int:group_id>/detail/', bot_api.telegram_group_filter_detail, name='telegram-group-detail'),
    path('telegram/groups/<int:group_id>/', bot_api.update_telegram_group_filter, name='telegram-group-update'),
    path('telegram/messages/send/', bot_api.send_telegram_chat_message, name='telegram-message-send'),
    path('telegram/messages/', bot_api.telegram_chat_messages, name='telegram-chat-messages'),
    path('bot/operation-logs/', bot_api.bot_operation_logs, name='bot-operation-logs'),
    path('products/', bot_api.products_list, name='products-list'),
    path('products/create/', bot_api.create_product, name='product-create'),
    path('products/<int:product_id>/', bot_api.update_product, name='product-update'),
    path('orders/', orders_api.orders_list, name='orders-list'),
    path('recharges/', orders_api.recharges_list, name='recharges-list'),
    path('recharges/<int:recharge_id>/', orders_api.recharge_detail, name='recharge-detail'),
    path('recharges/<int:recharge_id>/status/', orders_api.update_recharge_status, name='recharge-status-update'),
    path('tasks/', cloud_task_api.tasks_overview, name='tasks-overview'),
    path('tasks/center/', cloud_task_center.task_center_overview, name='task-center-overview'),
    path('tasks/plans/', bot_api.lifecycle_plans, name='lifecycle-plans'),
    path('tasks/plans/refresh/', bot_api.refresh_lifecycle_plan_view, name='lifecycle-plans-refresh'),
    path('tasks/plans/notes/', bot_api.update_lifecycle_plan_note, name='lifecycle-plan-note-update'),
    path('tasks/plans/server-assets/<int:asset_id>/shutdown/run/', bot_api.run_server_asset_shutdown_plan, name='lifecycle-plan-server-asset-shutdown-run'),
    path('tasks/plans/orphan-assets/<int:asset_id>/run/', bot_api.run_orphan_asset_delete_plan, name='lifecycle-plan-orphan-asset-run'),
    path('tasks/plans/unattached-ips/<int:asset_id>/run/', bot_api.run_unattached_ip_delete_plan, name='lifecycle-plan-unattached-ip-run'),
    path('tasks/notices/', cloud_task_api.notice_task_detail, name='notice-task-detail'),
    path('tasks/notices/refresh/', cloud_task_api.refresh_notice_plan_view, name='notice-task-refresh'),
    path('tasks/notices/switches/', cloud_task_api.update_notice_switches, name='notice-task-switches-update'),
    path('tasks/notices/history/<str:identifier>/delete/', cloud_task_api.delete_notice_history, name='notice-history-delete'),
    path('tasks/notices/text/', cloud_task_api.update_notice_plan_text, name='notice-task-text-update'),
    path('tasks/auto-renew/', cloud_task_api.auto_renew_task_detail, name='auto-renew-task-detail'),
    path('tasks/auto-renew/run/', cloud_task_api.run_auto_renew_tasks, name='auto-renew-task-run'),
    path('tasks/auto-renew/orders/<int:order_id>/run/', cloud_task_api.run_auto_renew_order, name='auto-renew-order-run'),
    path('cloud-assets/', cloud_asset_api.cloud_assets_list, name='cloud-assets-list'),
    path('cloud-assets/risk-summary/', cloud_asset_api.cloud_assets_risk_summary, name='cloud-assets-risk-summary'),
    path('cloud-assets/<int:asset_id>/', cloud_asset_edit_api.update_cloud_asset, name='cloud-asset-update'),
    path('cloud-assets/<int:asset_id>/auto-renew/', cloud_asset_edit_api.toggle_cloud_asset_auto_renew, name='cloud-asset-auto-renew'),
    path('cloud-assets/<int:asset_id>/sync/', cloud_sync_api.sync_cloud_asset_status, name='cloud-asset-sync'),
    path('cloud-assets/<int:asset_id>/delete/', cloud_asset_edit_api.delete_cloud_asset, name='cloud-asset-delete'),
    path('cloud-assets/ip-logs/', cloud_monitor_api.cloud_ip_logs_list, name='cloud-ip-logs-list'),
    path('cloud-assets/sync-status/', cloud_sync_jobs.cloud_assets_sync_status, name='cloud-assets-sync-status'),
    path('cloud-assets/sync-jobs/', cloud_sync_jobs.cloud_asset_sync_jobs_list, name='cloud-assets-sync-jobs-list'),
    path('cloud-assets/sync-jobs/metrics/', cloud_sync_jobs.cloud_asset_sync_jobs_metrics, name='cloud-assets-sync-jobs-metrics'),
    path('cloud-assets/sync-jobs/<int:job_id>/', cloud_sync_jobs.cloud_asset_sync_job_detail, name='cloud-assets-sync-job-detail'),
    path('cloud-assets/sync-jobs/<int:job_id>/cancel/', cloud_sync_jobs.cancel_cloud_asset_sync_job, name='cloud-assets-sync-job-cancel'),
    path('cloud-assets/sync-jobs/<int:job_id>/retry/', cloud_sync_jobs.retry_cloud_asset_sync_job, name='cloud-assets-sync-job-retry'),
    path('cloud-assets/sync/', cloud_sync_jobs.sync_cloud_assets, name='cloud-assets-sync'),
    path('cloud-orders/', cloud_order_api.cloud_orders_list, name='cloud-orders-list'),
    path('cloud-orders/<int:order_id>/', cloud_order_api.cloud_order_detail, name='cloud-order-detail'),
    path('cloud-orders/<int:order_id>/status/', cloud_order_api.update_cloud_order_status, name='cloud-order-status-update'),
    path('cloud-orders/<int:order_id>/delete/', cloud_order_api.delete_cloud_order, name='cloud-order-delete'),
    path('servers/', cloud_server_api.servers_list, name='servers-list'),
    path('servers/<int:server_id>/delete/', cloud_server_api.delete_server, name='server-delete'),
    path('servers/<int:server_id>/rebuild-preserve-link/', cloud_server_api.rebuild_server_preserve_link, name='server-rebuild-preserve-link'),
    path('servers/statistics/', cloud_server_api.servers_statistics, name='servers-statistics'),
    path('servers/sync/', cloud_sync_api.sync_servers, name='servers-sync'),
    path('settings/site-configs/', bot_api.site_configs_list, name='site-configs-list'),
    path('settings/site-configs/groups/', bot_api.site_config_groups, name='site-config-groups'),
    path('settings/site-configs/init/', bot_api.init_site_configs, name='site-configs-init'),
    path('settings/site-configs/init-texts/', bot_api.init_text_site_configs, name='site-configs-init-texts'),
    path('settings/site-configs/daily-expiry-summary/test/', bot_api.send_daily_expiry_summary_test_notification, name='site-config-daily-expiry-summary-test'),
    path('settings/site-configs/<int:config_id>/', bot_api.update_site_config, name='site-config-update'),
    path('settings/buttons/', bot_api.button_config_detail, name='button-config-detail'),
    path('settings/buttons/update/', bot_api.update_button_config, name='button-config-update'),
    path('settings/buttons/init/', bot_api.init_button_config_view, name='button-config-init'),
    path('settings/cloud-accounts/', bot_api.cloud_accounts_list, name='cloud-accounts-list'),
    path('settings/cloud-accounts/create/', bot_api.create_cloud_account, name='cloud-account-create'),
    path('settings/cloud-accounts/<int:account_id>/', bot_api.update_cloud_account, name='cloud-account-update'),
    path('settings/cloud-accounts/<int:account_id>/delete/', bot_api.delete_cloud_account, name='cloud-account-delete'),
    path('settings/cloud-accounts/<int:account_id>/verify/', bot_api.verify_cloud_account, name='cloud-account-verify'),
    path('settings/admin-users/', bot_api.admin_users_list, name='admin-users-list'),
    path('settings/admin-users/create/', bot_api.create_admin_user, name='admin-user-create'),
    path('settings/admin-users/<int:user_id>/', bot_api.update_admin_user, name='admin-user-update'),
    path('settings/admin-users/<int:user_id>/delete/', bot_api.delete_admin_user, name='admin-user-delete'),
    path('settings/password/change/', bot_api.change_my_password, name='password-change'),
    path('cloud-plans/', cloud_plan_api.cloud_plans_list, name='cloud-plans-list'),
    path('cloud-pricing/', cloud_plan_api.cloud_pricing_list, name='cloud-pricing-list'),
    path('cloud-plans/sync/', cloud_sync_api.sync_cloud_plans, name='cloud-plans-sync'),
    path('cloud-plans/create/', cloud_plan_api.create_cloud_plan, name='cloud-plan-create'),
    path('cloud-plans/<int:plan_id>/', cloud_plan_api.update_cloud_plan, name='cloud-plan-update'),
    path('cloud-plans/<int:plan_id>/delete/', cloud_plan_api.delete_cloud_plan, name='cloud-plan-delete'),
    path('monitors/', cloud_monitor_api.monitors_list, name='monitors-list'),
]
