# Generated by Django 5.2.13 on 2026-04-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recharge',
            table='order_recharge',
        ),
    ]
