# Generated by Django 5.2.13 on 2026-04-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_add_expired_grace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudserverplan',
            name='plan_description',
            field=models.TextField(blank=True, null=True, verbose_name='套餐描述'),
        ),
        migrations.CreateModel(
            name='CloudServerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aws_lightsail', 'AWS 光帆服务器'), ('aliyun_simple', '阿里云轻量云')], db_index=True, max_length=32, verbose_name='云厂商')),
                ('region_code', models.CharField(db_index=True, max_length=64, verbose_name='地区代码')),
                ('region_name', models.CharField(max_length=128, verbose_name='地区名称')),
                ('bundle_code', models.CharField(db_index=True, max_length=128, verbose_name='规格代码')),
                ('plan_name', models.CharField(max_length=191, verbose_name='套餐名称')),
                ('plan_description', models.TextField(blank=True, null=True, verbose_name='套餐描述')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('storage', models.CharField(blank=True, max_length=64, null=True, verbose_name='存储')),
                ('bandwidth', models.CharField(blank=True, max_length=64, null=True, verbose_name='带宽')),
                ('price', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='销售价格')),
                ('currency', models.CharField(default='USDT', max_length=32, verbose_name='币种')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '云服务器价格配置',
                'verbose_name_plural': '云服务器价格配置',
                'db_table': 'cloud_server_pricing',
                'ordering': ['provider', 'region_name', '-sort_order', 'id'],
                'unique_together': {('provider', 'region_code', 'bundle_code')},
            },
        ),
    ]
