# Generated by Django 5.2.13 on 2026-04-19 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_cloud_reminders_and_replacement'),
        ('mall', '0015_cart_item'),
    ]

    operations = [
    ]
