# Generated by Django 5.2.13 on 2026-04-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0017_cloud_plan_cost_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudserverplan',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='出售价'),
        ),
    ]
