# Generated by Django 5.2.13 on 2026-04-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0023_drop_legacy_cloud_server_pricing'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='CloudServerPricing',
                ),
            ],
        ),
    ]
