# Generated by Django 5.2.13 on 2026-04-23 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0024_delete_cloudserverpricing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='order_cart_item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order_order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='order_product',
        ),
    ]
