# Generated by Django 5.2.13 on 2026-04-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0025_alter_cartitem_table_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cloudasset',
            table='cloud_asset',
        ),
        migrations.AlterModelTable(
            name='cloudserverorder',
            table='cloud_order',
        ),
        migrations.AlterModelTable(
            name='cloudserverplan',
            table='cloud_plan',
        ),
        migrations.AlterModelTable(
            name='server',
            table='cloud_server',
        ),
        migrations.AlterModelTable(
            name='serverprice',
            table='cloud_price',
        ),
    ]
