# Generated by Django 5.2.13 on 2026-04-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0029_move_product_cart_order_to_orders'),
        ('orders', '0004_alter_cartitem_cloud_plan'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
            model_name='cloudasset',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cloudasset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cloudiplog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='cloudiplog',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cloudiplog',
            name='server',
        ),
        migrations.RemoveField(
            model_name='cloudiplog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cloudserverorder',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='cloudserverorder',
            name='replacement_for',
        ),
        migrations.RemoveField(
            model_name='cloudserverorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='server',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='cloudserverplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='server',
            name='user',
        ),
        migrations.DeleteModel(
            name='ServerPrice',
        ),
        migrations.DeleteModel(
            name='CloudAsset',
        ),
        migrations.DeleteModel(
            name='CloudIpLog',
        ),
        migrations.DeleteModel(
            name='CloudServerPlan',
        ),
        migrations.DeleteModel(
            name='CloudServerOrder',
        ),
                migrations.DeleteModel(
            name='Server',
        ),
            ],
        ),
    ]
