# Generated by Django 5.2.13 on 2026-04-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260418_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='cloud_discount_rate',
            field=models.DecimalField(decimal_places=2, default=100, help_text='百分比，100 表示无折扣，90 表示 9 折', max_digits=5, verbose_name='云服务器专属折扣'),
        ),
    ]
