# Generated by Django 5.2.13 on 2026-04-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_deprecate_telegramusername_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balanceledger',
            table='order_balance_ledger',
        ),
        migrations.AlterModelTable(
            name='telegramuser',
            table='bot_user',
        ),
    ]
