# Generated by OpenClaw

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_telegram_login_account_notify_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField(db_index=True, verbose_name='Telegram用户ID')),
                ('chat_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='会话ID')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='消息ID')),
                ('action_type', models.CharField(choices=[('message', '发送消息'), ('callback', '点击按钮')], db_index=True, max_length=32, verbose_name='操作类型')),
                ('action_label', models.CharField(blank=True, max_length=191, null=True, verbose_name='操作说明')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='操作内容')),
                ('username_snapshot', models.CharField(blank=True, db_index=True, max_length=191, null=True, verbose_name='用户名快照')),
                ('first_name_snapshot', models.CharField(blank=True, max_length=191, null=True, verbose_name='昵称快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='bot.telegramuser', verbose_name='Telegram用户')),
            ],
            options={
                'verbose_name': '机器人操作日志',
                'verbose_name_plural': '机器人操作日志',
                'db_table': 'bot_operation_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='botoperationlog',
            index=models.Index(fields=['tg_user_id', '-created_at'], name='idx_bot_op_user_time'),
        ),
        migrations.AddIndex(
            model_name='botoperationlog',
            index=models.Index(fields=['action_type', '-created_at'], name='idx_bot_op_action_time'),
        ),
    ]
