# Generated by Django 5.2.13 on 2026-06-03 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_telegramgroupfilter_archived'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='adminreplylink',
            table_comment='管理员消息与用户会话回复映射表',
        ),
        migrations.AlterModelTableComment(
            name='botoperationlog',
            table_comment='Telegram 机器人用户操作日志表',
        ),
        migrations.AlterModelTableComment(
            name='telegramchatarchive',
            table_comment='Telegram 会话归档表',
        ),
        migrations.AlterModelTableComment(
            name='telegramchatmessage',
            table_comment='Telegram 聊天消息归档表',
        ),
        migrations.AlterModelTableComment(
            name='telegramgroupfilter',
            table_comment='Telegram 群组转发和推送过滤表',
        ),
        migrations.AlterModelTableComment(
            name='telegramloginaccount',
            table_comment='Telegram 登录账号和会话配置表',
        ),
        migrations.AlterModelTableComment(
            name='telegramuser',
            table_comment='Telegram 用户账户和余额表',
        ),
        migrations.AlterField(
            model_name='adminreplylink',
            name='admin_chat_id',
            field=models.BigIntegerField(db_comment='管理员会话ID', db_index=True, verbose_name='管理员会话ID'),
        ),
        migrations.AlterField(
            model_name='adminreplylink',
            name='admin_message_id',
            field=models.BigIntegerField(db_comment='管理员消息ID', db_index=True, verbose_name='管理员消息ID'),
        ),
        migrations.AlterField(
            model_name='adminreplylink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='adminreplylink',
            name='is_active',
            field=models.BooleanField(db_comment='启用', db_index=True, default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='adminreplylink',
            name='source_content_type',
            field=models.CharField(db_comment='原消息类型', default='text', max_length=32, verbose_name='原消息类型'),
        ),
        migrations.AlterField(
            model_name='adminreplylink',
            name='user',
            field=models.ForeignKey(db_comment='Telegram用户', on_delete=django.db.models.deletion.CASCADE, related_name='admin_reply_links', to='bot.telegramuser', verbose_name='Telegram用户'),
        ),
        migrations.AlterField(
            model_name='adminreplylink',
            name='user_chat_id',
            field=models.BigIntegerField(db_comment='用户会话ID', db_index=True, verbose_name='用户会话ID'),
        ),
        migrations.AlterField(
            model_name='adminreplylink',
            name='user_message_id',
            field=models.BigIntegerField(blank=True, db_comment='用户消息ID', null=True, verbose_name='用户消息ID'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='action_label',
            field=models.CharField(blank=True, db_comment='操作说明', max_length=191, null=True, verbose_name='操作说明'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='action_type',
            field=models.CharField(choices=[('message', '发送消息'), ('callback', '点击按钮')], db_comment='操作类型', db_index=True, max_length=32, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='chat_id',
            field=models.BigIntegerField(blank=True, db_comment='会话ID', db_index=True, null=True, verbose_name='会话ID'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='first_name_snapshot',
            field=models.CharField(blank=True, db_comment='昵称快照', max_length=191, null=True, verbose_name='昵称快照'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='message_id',
            field=models.BigIntegerField(blank=True, db_comment='消息ID', null=True, verbose_name='消息ID'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='payload',
            field=models.TextField(blank=True, db_comment='操作内容', null=True, verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='tg_user_id',
            field=models.BigIntegerField(db_comment='Telegram用户ID', db_index=True, verbose_name='Telegram用户ID'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='Telegram用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='bot.telegramuser', verbose_name='Telegram用户'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='username_snapshot',
            field=models.CharField(blank=True, db_comment='用户名快照', db_index=True, max_length=191, null=True, verbose_name='用户名快照'),
        ),
        migrations.AlterField(
            model_name='telegramchatarchive',
            name='chat_id',
            field=models.BigIntegerField(db_comment='会话ID', db_index=True, unique=True, verbose_name='会话ID'),
        ),
        migrations.AlterField(
            model_name='telegramchatarchive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='归档时间', verbose_name='归档时间'),
        ),
        migrations.AlterField(
            model_name='telegramchatarchive',
            name='note',
            field=models.TextField(blank=True, db_comment='备注', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='telegramchatarchive',
            name='title',
            field=models.CharField(blank=True, db_comment='会话标题', max_length=191, null=True, verbose_name='会话标题'),
        ),
        migrations.AlterField(
            model_name='telegramchatarchive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='chat_id',
            field=models.BigIntegerField(db_comment='会话ID', db_index=True, verbose_name='会话ID'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='chat_title',
            field=models.CharField(blank=True, db_comment='会话标题', max_length=191, null=True, verbose_name='会话标题'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='content_type',
            field=models.CharField(db_comment='消息类型', default='text', max_length=32, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='direction',
            field=models.CharField(choices=[('in', '收到'), ('out', '发出')], db_comment='方向', db_index=True, default='in', max_length=8, verbose_name='方向'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='first_name_snapshot',
            field=models.CharField(blank=True, db_comment='昵称快照', max_length=191, null=True, verbose_name='昵称快照'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='login_account',
            field=models.ForeignKey(blank=True, db_comment='登录账号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='bot.telegramloginaccount', verbose_name='登录账号'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='message_id',
            field=models.BigIntegerField(blank=True, db_comment='消息ID', null=True, verbose_name='消息ID'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='source',
            field=models.CharField(db_comment='来源', db_index=True, default='bot', max_length=32, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='text',
            field=models.TextField(blank=True, db_comment='消息内容', null=True, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='tg_user_id',
            field=models.BigIntegerField(db_comment='Telegram用户ID', db_index=True, verbose_name='Telegram用户ID'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='Telegram用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='bot.telegramuser', verbose_name='Telegram用户'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='username_snapshot',
            field=models.CharField(blank=True, db_comment='用户名快照', db_index=True, max_length=191, null=True, verbose_name='用户名快照'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='archived',
            field=models.BooleanField(db_comment='归档', db_index=True, default=False, verbose_name='归档'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='chat_id',
            field=models.BigIntegerField(db_comment='群组会话ID', db_index=True, unique=True, verbose_name='群组会话ID'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='collapsed',
            field=models.BooleanField(db_comment='折叠', db_index=True, default=False, verbose_name='折叠'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='enabled',
            field=models.BooleanField(db_comment='允许转发', db_index=True, default=False, verbose_name='允许转发'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='push_enabled',
            field=models.BooleanField(db_comment='允许推送', db_index=True, default=False, verbose_name='允许推送'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='title',
            field=models.CharField(blank=True, db_comment='群组名称', max_length=191, null=True, verbose_name='群组名称'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='username',
            field=models.CharField(blank=True, db_comment='群组用户名', db_index=True, max_length=191, null=True, verbose_name='群组用户名'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='label',
            field=models.CharField(db_comment='账号备注', max_length=191, verbose_name='账号备注'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, db_comment='最近同步时间', null=True, verbose_name='最近同步时间'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='listener_push_enabled',
            field=models.BooleanField(db_comment='个人号监听推送', db_index=True, default=True, verbose_name='个人号监听推送'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='note',
            field=models.TextField(blank=True, db_comment='备注', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='notify_enabled',
            field=models.BooleanField(db_comment='允许通知', db_index=True, default=True, verbose_name='允许通知'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='phone',
            field=models.CharField(blank=True, db_comment='手机号', max_length=64, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='phone_code_hash',
            field=models.CharField(blank=True, db_comment='加密存储的Telegram验证码哈希', max_length=191, null=True, verbose_name='验证码哈希'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='session_string',
            field=models.TextField(blank=True, db_comment='加密存储的Telegram会话字符串', null=True, verbose_name='Telegram会话'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='status',
            field=models.CharField(db_comment='状态', db_index=True, default='pending', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='tg_user_id',
            field=models.BigIntegerField(blank=True, db_comment='Telegram 用户ID', db_index=True, null=True, verbose_name='Telegram 用户ID'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='username',
            field=models.CharField(blank=True, db_comment='用户名', max_length=191, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='admin_forward_muted_until',
            field=models.DateTimeField(blank=True, db_comment='管理员转发静默到', db_index=True, null=True, verbose_name='管理员转发静默到'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='balance',
            field=models.DecimalField(db_comment='用户USDT可用余额', decimal_places=6, default=0, max_digits=18, verbose_name='USDT余额'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='balance_trx',
            field=models.DecimalField(db_comment='用户TRX可用余额', decimal_places=6, default=0, max_digits=18, verbose_name='TRX余额'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='cloud_discount_rate',
            field=models.DecimalField(db_comment='云服务器折扣百分比，100表示无折扣', decimal_places=2, default=100, help_text='百分比，100 表示无折扣，90 表示 9 折', max_digits=5, verbose_name='云服务器专属折扣'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='cloud_reminder_muted_until',
            field=models.DateTimeField(blank=True, db_comment='云服务器提醒静默到', null=True, verbose_name='云服务器提醒静默到'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, db_comment='昵称', max_length=191, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_user_id',
            field=models.BigIntegerField(db_comment='Telegram 用户唯一数字ID', db_index=True, unique=True, verbose_name='Telegram 用户ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.TextField(blank=True, db_comment='用户名集合', null=True, verbose_name='用户名集合'),
        ),
    ]
