# Generated by Django 5.2.13 on 2026-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_adminreplylink_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchatarchive',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
