# Generated by Django 5.2.13 on 2026-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_telegramchatarchive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreplylink',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='botoperationlog',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramchatmessage',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramgroupfilter',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramloginaccount',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
