# Generated by Django 5.2.13 on 2026-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_adminreplylink_id_alter_botoperationlog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTelegramUserSlot',
            fields=[
                ('id', models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('reusable_user_id', models.BigIntegerField(db_comment='已删除用户释放出的 bot_user.id', db_index=True, unique=True, verbose_name='可复用用户ID')),
                ('deleted_tg_user_id', models.BigIntegerField(blank=True, db_comment='删除前的 Telegram 用户ID', db_index=True, null=True, verbose_name='原 Telegram 用户ID')),
                ('deleted_username', models.TextField(blank=True, db_comment='删除前的用户名集合', null=True, verbose_name='原用户名集合')),
                ('deleted_first_name', models.CharField(blank=True, db_comment='删除前的昵称', max_length=191, null=True, verbose_name='原昵称')),
                ('note', models.TextField(blank=True, db_comment='备注', null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '已删除用户ID槽位',
                'verbose_name_plural': '已删除用户ID槽位',
                'db_table': 'bot_deleted_telegram_user_slot',
                'db_table_comment': '已删除 Telegram 用户 ID 复用槽位表',
                'ordering': ['created_at', 'reusable_user_id'],
            },
        ),
    ]
