from django.urls import path

from . import views

app_name = 'dashboard_api'

urlpatterns = [
    path('csrf/', views.csrf, name='csrf'),
    path('auth/login', views.auth_login, name='auth-login'),
    path('auth/logout', views.auth_logout, name='auth-logout'),
    path('auth/refresh', views.auth_refresh, name='auth-refresh'),
    path('auth/codes', views.auth_codes, name='auth-codes'),
    path('user/info', views.user_info, name='user-info'),
    path('dashboard/me/', views.me, name='me'),
    path('dashboard/overview/', views.overview, name='overview'),
    path('users/', views.users_list, name='users-list'),
    path('users/<int:user_id>/balance/', views.update_user_balance, name='user-balance-update'),
    path('users/<int:user_id>/discount/', views.update_user_discount, name='user-discount-update'),
    path('users/<int:user_id>/balance-details/', views.user_balance_details, name='user-balance-details'),
    path('products/', views.products_list, name='products-list'),
    path('orders/', views.orders_list, name='orders-list'),
    path('tasks/', views.tasks_overview, name='tasks-overview'),
    path('task-list/', views.tasks_overview, name='task-list-compat'),
    path('products/create/', views.create_product, name='product-create'),
    path('products/<int:product_id>/', views.update_product, name='product-update'),
    path('cloud-assets/', views.cloud_assets_list, name='cloud-assets-list'),
    path('cloud-assets/sync/', views.sync_cloud_assets, name='cloud-assets-sync'),
    path('cloud-orders/', views.cloud_orders_list, name='cloud-orders-list'),
    path('cloud-orders/<int:order_id>/', views.cloud_order_detail, name='cloud-order-detail'),
    path('cloud-orders/<int:order_id>/status/', views.update_cloud_order_status, name='cloud-order-status-update'),
    path('servers/', views.servers_list, name='servers-list'),
    path('servers/<int:server_id>/delete/', views.delete_server, name='server-delete'),
    path('servers/statistics/', views.servers_statistics, name='servers-statistics'),
    path('servers/sync/', views.sync_servers, name='servers-sync'),
    path('settings/site-configs/', views.site_configs_list, name='site-configs-list'),
    path('settings/site-configs/groups/', views.site_config_groups, name='site-config-groups'),
    path('settings/site-configs/init/', views.init_site_configs, name='site-configs-init'),
    path('settings/site-configs/<int:config_id>/', views.update_site_config, name='site-config-update'),
    path('settings/cloud-accounts/', views.cloud_accounts_list, name='cloud-accounts-list'),
    path('settings/cloud-accounts/create/', views.create_cloud_account, name='cloud-account-create'),
    path('settings/cloud-accounts/<int:account_id>/', views.update_cloud_account, name='cloud-account-update'),
    path('settings/cloud-accounts/<int:account_id>/delete/', views.delete_cloud_account, name='cloud-account-delete'),
    path('settings/cloud-accounts/<int:account_id>/verify/', views.verify_cloud_account, name='cloud-account-verify'),
    path('cloud-plans/', views.cloud_plans_list, name='cloud-plans-list'),
    path('cloud-pricing/', views.cloud_pricing_list, name='cloud-pricing-list'),
    path('plan-settings/', views.cloud_plans_list, name='plan-settings-compat'),
    path('cloud-plans/sync/', views.sync_cloud_plans, name='cloud-plans-sync'),
    path('cloud-plans/create/', views.create_cloud_plan, name='cloud-plan-create'),
    path('cloud-plans/<int:plan_id>/', views.update_cloud_plan, name='cloud-plan-update'),
    path('cloud-plans/<int:plan_id>/delete/', views.delete_cloud_plan, name='cloud-plan-delete'),
    path('recharges/', views.recharges_list, name='recharges-list'),
    path('recharges/<int:recharge_id>/', views.recharge_detail, name='recharge-detail'),
    path('recharges/<int:recharge_id>/status/', views.update_recharge_status, name='recharge-status-update'),
    path('monitors/', views.monitors_list, name='monitors-list'),
]
