# Generated by Django 5.2.13 on 2026-04-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addressmonitor',
            table='cloud_address_monitor',
        ),
        migrations.AlterModelTable(
            name='dailyaddressstat',
            table='cloud_address_stat_daily',
        ),
        migrations.AlterModelTable(
            name='resourcesnapshot',
            table='cloud_resource_snapshot',
        ),
    ]
