# Generated by Django 5.2.13 on 2026-04-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_switch_user_fk_to_bot'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
            model_name='dailyaddressstat',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='resourcesnapshot',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='dailyaddressstat',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddressMonitor',
        ),
        migrations.DeleteModel(
            name='ResourceSnapshot',
        ),
                migrations.DeleteModel(
            name='DailyAddressStat',
        ),
            ],
        ),
    ]
