# Generated by Django 5.2.13 on 2026-04-24 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
        ('orders', '0003_move_product_cart_order_from_mall'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='cartitem',
                    name='cloud_plan',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cloud.cloudserverplan', verbose_name='云套餐'),
                ),
            ],
        ),
    ]
