# Generated by Django 5.2.13 on 2026-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartitem_cloud_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_address',
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True, verbose_name='链上付款地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='receive_address',
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True, verbose_name='链上收款地址'),
        ),
        migrations.AddField(
            model_name='recharge',
            name='payer_address',
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True, verbose_name='链上付款地址'),
        ),
        migrations.AddField(
            model_name='recharge',
            name='receive_address',
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True, verbose_name='链上收款地址'),
        ),
    ]
