# Generated by Django 5.2.13 on 2026-06-03 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_adminreplylink_table_comment_and_more'),
        ('cloud', '0050_alter_addressmonitor_table_comment_and_more'),
        ('orders', '0005_chain_payment_trace'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='balanceledger',
            table_comment='用户余额变动流水表',
        ),
        migrations.AlterModelTableComment(
            name='cartitem',
            table_comment='用户购物车明细表',
        ),
        migrations.AlterModelTableComment(
            name='order',
            table_comment='普通商品订单表',
        ),
        migrations.AlterModelTableComment(
            name='product',
            table_comment='普通商品配置表',
        ),
        migrations.AlterModelTableComment(
            name='recharge',
            table_comment='用户链上充值记录表',
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='after_balance',
            field=models.DecimalField(db_comment='变动后该币种可用余额', decimal_places=9, max_digits=18, verbose_name='变动后余额'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='amount',
            field=models.DecimalField(db_comment='本次余额变动金额', decimal_places=9, max_digits=18, verbose_name='变动金额'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='before_balance',
            field=models.DecimalField(db_comment='变动前该币种可用余额', decimal_places=9, max_digits=18, verbose_name='变动前余额'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('TRX', 'TRX')], db_comment='币种', db_index=True, max_length=32, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='description',
            field=models.TextField(blank=True, db_comment='说明', null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='direction',
            field=models.CharField(choices=[('in', '收入'), ('out', '支出')], db_comment='方向', db_index=True, max_length=16, verbose_name='方向'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='operator',
            field=models.CharField(blank=True, db_comment='操作人', max_length=191, null=True, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='related_id',
            field=models.BigIntegerField(blank=True, db_comment='关联ID', db_index=True, null=True, verbose_name='关联ID'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='related_type',
            field=models.CharField(blank=True, db_comment='关联类型', db_index=True, max_length=64, null=True, verbose_name='关联类型'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='type',
            field=models.CharField(choices=[('manual_adjust', '手动调整'), ('recharge', '充值入账'), ('order_balance_pay', '商品余额支付'), ('cloud_order_balance_pay', '云服务器余额支付')], db_comment='类型', db_index=True, max_length=64, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='balanceledger',
            name='user',
            field=models.ForeignKey(db_comment='用户', on_delete=django.db.models.deletion.CASCADE, related_name='balance_ledgers', to='bot.telegramuser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cloud_plan',
            field=models.ForeignKey(blank=True, db_comment='云套餐', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cloud.cloudserverplan', verbose_name='云套餐'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(choices=[('product', '商品'), ('cloud_plan', '云套餐')], db_comment='项目类型', default='product', max_length=32, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, db_comment='商品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='orders.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(db_comment='数量', default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(db_comment='用户', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='bot.telegramuser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('TRX', 'TRX')], db_comment='币种', db_index=True, default='USDT', max_length=32, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expired_at',
            field=models.DateTimeField(blank=True, db_comment='过期时间', null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(db_comment='普通商品订单唯一编号', db_index=True, max_length=191, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_comment='支付时间', null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_amount',
            field=models.DecimalField(blank=True, db_comment='余额或链上支付的最终应付金额', decimal_places=9, max_digits=18, null=True, verbose_name='应付金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('balance', '余额支付'), ('address', '地址支付')], db_comment='支付方式', max_length=32, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payer_address',
            field=models.CharField(blank=True, db_comment='链上付款地址', db_index=True, max_length=191, null=True, verbose_name='链上付款地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(db_comment='商品', on_delete=django.db.models.deletion.PROTECT, to='orders.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.TextField(db_comment='商品名称', verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(db_comment='数量', default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_address',
            field=models.CharField(blank=True, db_comment='链上收款地址', db_index=True, max_length=191, null=True, verbose_name='链上收款地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('delivered', '已发货'), ('cancelled', '已取消'), ('expired', '已过期')], db_comment='状态', db_index=True, default='pending', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(db_comment='总金额', decimal_places=6, max_digits=18, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tx_hash',
            field=models.CharField(blank=True, db_comment='普通商品订单链上支付交易哈希', max_length=191, null=True, unique=True, verbose_name='交易哈希'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_comment='用户', on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_image',
            field=models.TextField(blank=True, db_comment='图片File ID/URL', null=True, verbose_name='图片File ID/URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_text',
            field=models.TextField(blank=True, db_comment='文本内容', null=True, verbose_name='文本内容'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频')], db_comment='内容类型', default='text', max_length=32, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_video',
            field=models.TextField(blank=True, db_comment='视频File ID/URL', null=True, verbose_name='视频File ID/URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_comment='商品描述', null=True, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_comment='上架', default=True, verbose_name='上架'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(db_comment='商品名称', verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_comment='商品单价(USDT)', decimal_places=6, max_digits=18, verbose_name='商品单价(USDT)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(db_comment='排序', default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(db_comment='库存', default=-1, help_text='-1 表示无限库存', verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='amount',
            field=models.DecimalField(db_comment='充值金额', decimal_places=6, max_digits=18, verbose_name='充值金额'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_comment='完成时间', null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('TRX', 'TRX')], db_comment='币种', db_index=True, default='USDT', max_length=32, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='expired_at',
            field=models.DateTimeField(blank=True, db_comment='过期时间', null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='pay_amount',
            field=models.DecimalField(db_comment='链上实际应支付金额', decimal_places=9, max_digits=18, verbose_name='支付金额'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='payer_address',
            field=models.CharField(blank=True, db_comment='链上付款地址', db_index=True, max_length=191, null=True, verbose_name='链上付款地址'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='receive_address',
            field=models.CharField(blank=True, db_comment='链上收款地址', db_index=True, max_length=191, null=True, verbose_name='链上收款地址'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('completed', '已完成'), ('expired', '已过期')], db_comment='状态', db_index=True, default='pending', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='tx_hash',
            field=models.CharField(blank=True, db_comment='链上充值交易哈希，去重入账依据', max_length=191, null=True, unique=True, verbose_name='交易哈希'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='user',
            field=models.ForeignKey(db_comment='用户', on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='用户'),
        ),
    ]
