# Generated by Django 5.2.13 on 2026-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_balanceledger_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceledger',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
