# Generated by Django 5.2.13 on 2026-04-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=191, verbose_name='监控地址')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('usdt_threshold', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='USDT阈值')),
                ('trx_threshold', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='TRX阈值')),
                ('daily_income', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='今日收入')),
                ('daily_expense', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='今日支出')),
                ('daily_income_currency', models.CharField(default='USDT', max_length=32, verbose_name='收入币种')),
                ('daily_expense_currency', models.CharField(default='USDT', max_length=32, verbose_name='支出币种')),
                ('stats_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='统计日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '地址监控',
                'verbose_name_plural': '地址监控',
                'db_table': 'address_monitors',
                'ordering': ['-created_at'],
            },
        ),
    ]
