# Generated by Django 5.2.13 on 2026-04-24 10:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='AddressMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=191, verbose_name='监控地址')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('monitor_transfers', models.BooleanField(default=True, verbose_name='监控转账')),
                ('monitor_resources', models.BooleanField(default=False, verbose_name='监控资源')),
                ('last_energy', models.BigIntegerField(default=0, verbose_name='上次可用能量')),
                ('last_bandwidth', models.BigIntegerField(default=0, verbose_name='上次可用带宽')),
                ('resource_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='资源检查时间')),
                ('usdt_threshold', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='USDT阈值')),
                ('trx_threshold', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='TRX阈值')),
                ('daily_income', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='今日收入')),
                ('daily_expense', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='今日支出')),
                ('daily_income_currency', models.CharField(default='USDT', max_length=32, verbose_name='收入币种')),
                ('daily_expense_currency', models.CharField(default='USDT', max_length=32, verbose_name='支出币种')),
                ('stats_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='统计日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '地址监控',
                'verbose_name_plural': '地址监控',
                'db_table': 'cloud_address_monitor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_scope', models.CharField(choices=[('platform', '平台账户'), ('user', '用户账户'), ('cloud', '云账户')], db_index=True, default='platform', max_length=32, verbose_name='账户归属类型')),
                ('account_key', models.CharField(blank=True, db_index=True, max_length=191, null=True, verbose_name='账户标识')),
                ('address', models.CharField(db_index=True, max_length=191, verbose_name='地址')),
                ('energy', models.BigIntegerField(default=0, verbose_name='可用能量')),
                ('bandwidth', models.BigIntegerField(default=0, verbose_name='可用带宽')),
                ('delta_energy', models.BigIntegerField(default=0, verbose_name='能量变化')),
                ('delta_bandwidth', models.BigIntegerField(default=0, verbose_name='带宽变化')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='采集时间')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_snapshots', to='cloud.addressmonitor', verbose_name='监控地址')),
            ],
            options={
                'verbose_name': '资源快照',
                'verbose_name_plural': '资源快照',
                'db_table': 'cloud_resource_snapshot',
                'ordering': ['-captured_at', '-id'],
            },
        ),
                migrations.CreateModel(
            name='DailyAddressStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_scope', models.CharField(choices=[('platform', '平台账户'), ('user', '用户账户'), ('cloud', '云账户')], db_index=True, default='platform', max_length=32, verbose_name='账户归属类型')),
                ('account_key', models.CharField(blank=True, db_index=True, max_length=191, null=True, verbose_name='账户标识')),
                ('address', models.CharField(db_index=True, max_length=191, verbose_name='地址')),
                ('currency', models.CharField(db_index=True, max_length=32, verbose_name='币种')),
                ('stats_date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('income', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='收入')),
                ('expense', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='支出')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_stats', to='cloud.addressmonitor', verbose_name='监控地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_address_stats', to='bot.telegramuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日地址统计',
                'verbose_name_plural': '每日地址统计',
                'db_table': 'cloud_address_stat_daily',
                'ordering': ['-stats_date', '-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'address', 'currency', 'stats_date', 'account_scope'), name='uniq_daily_address_stat_scope')],
            },
                ),
            ],
        ),
    ]
