# Generated by Django 5.2.13 on 2026-04-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_cloudserverplan_display_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprice',
            name='display_bandwidth',
            field=models.CharField(blank=True, max_length=64, verbose_name='展示带宽'),
        ),
        migrations.AddField(
            model_name='serverprice',
            name='display_cpu',
            field=models.CharField(blank=True, max_length=64, verbose_name='展示CPU'),
        ),
        migrations.AddField(
            model_name='serverprice',
            name='display_description',
            field=models.TextField(blank=True, verbose_name='展示说明'),
        ),
        migrations.AddField(
            model_name='serverprice',
            name='display_memory',
            field=models.CharField(blank=True, max_length=64, verbose_name='展示内存'),
        ),
        migrations.AddField(
            model_name='serverprice',
            name='display_plan_name',
            field=models.CharField(blank=True, max_length=191, verbose_name='展示套餐名'),
        ),
        migrations.AddField(
            model_name='serverprice',
            name='display_storage',
            field=models.CharField(blank=True, max_length=64, verbose_name='展示存储'),
        ),
    ]
