# Generated by OpenClaw

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0017_proxy_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudserverorder',
            name='ip_change_quota',
            field=models.IntegerField(default=0, verbose_name='剩余更换IP次数'),
        ),
    ]
