# Generated by OpenClaw

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0020_backfill_legacy_ip_change_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudserverorder',
            name='ip_change_quota',
            field=models.IntegerField(default=1, verbose_name='剩余更换IP次数'),
        ),
    ]
