# Generated by Django 5.0.14 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0025_cloudserverorder_auto_renew_notice_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudserverorder',
            name='auto_renew_failure_notice_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='自动续费失败通知发送时间'),
        ),
    ]
