# Generated by OpenClaw

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('cloud', '0030_cloudasset_telegram_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAutoRenewRetryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=191, verbose_name='订单号')),
                ('ip', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='公网IP')),
                ('status', models.CharField(choices=[('pending', '待重试'), ('succeeded', '已成功'), ('cancelled', '已取消'), ('failed', '重试失败')], db_index=True, default='pending', max_length=32, verbose_name='状态')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='失败原因')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='最后错误')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('next_check_at', models.DateTimeField(db_index=True, verbose_name='下次检查时间')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('succeeded_at', models.DateTimeField(blank=True, null=True, verbose_name='成功时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_renew_retry_tasks', to='cloud.cloudserverorder', verbose_name='云服务器订单')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_renew_retry_tasks', to='bot.telegramuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '自动续费重试任务',
                'verbose_name_plural': '自动续费重试任务',
                'db_table': 'cloud_auto_renew_retry_task',
                'ordering': ['next_check_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='cloudautorenewretrytask',
            index=models.Index(fields=['status', 'next_check_at'], name='idx_auto_renew_retry_due'),
        ),
        migrations.AddIndex(
            model_name='cloudautorenewretrytask',
            index=models.Index(fields=['order', 'status'], name='idx_auto_renew_retry_order'),
        ),
    ]
