# Generated by Django 5.2.13 on 2026-06-01 13:29

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0015_telegramgroupfilter_archived'),
        ('cloud', '0040_cloudasset_sync_state'),
        ('core', '0011_trongrid_api_key_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAssetDashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='列表载荷')),
                ('search_text', models.TextField(blank=True, verbose_name='搜索文本')),
                ('provider', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='云厂商')),
                ('account_label', models.CharField(blank=True, db_index=True, max_length=191, null=True, verbose_name='账户/来源标识')),
                ('region_code', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='地区代码')),
                ('public_ip', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='公网IP')),
                ('status', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='状态')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否活跃')),
                ('actual_expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='实际到期时间')),
                ('sort_order', models.IntegerField(db_index=True, default=99, verbose_name='排序')),
                ('tg_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram 用户ID')),
                ('group_user_key', models.CharField(db_index=True, max_length=191, verbose_name='用户分组键')),
                ('group_user_label', models.CharField(blank=True, max_length=191, verbose_name='用户分组标签')),
                ('group_telegram_key', models.CharField(db_index=True, max_length=191, verbose_name='群组分组键')),
                ('group_telegram_label', models.CharField(blank=True, max_length=191, verbose_name='群组分组标签')),
                ('risk_status', models.CharField(db_index=True, default='other', max_length=64, verbose_name='风险状态')),
                ('risk_rank', models.IntegerField(db_index=True, default=99, verbose_name='风险排序')),
                ('risk_statuses', models.JSONField(blank=True, default=list, verbose_name='风险状态集合')),
                ('risk_normal', models.BooleanField(db_index=True, default=False, verbose_name='运行中')),
                ('risk_due_soon', models.BooleanField(db_index=True, default=False, verbose_name='即将到期')),
                ('risk_expired', models.BooleanField(db_index=True, default=False, verbose_name='已过期')),
                ('risk_unattached_ip', models.BooleanField(db_index=True, default=False, verbose_name='未附加固定IP')),
                ('risk_abnormal', models.BooleanField(db_index=True, default=False, verbose_name='异常/待确认')),
                ('risk_account_disabled', models.BooleanField(db_index=True, default=False, verbose_name='云账号已停用')),
                ('risk_shutdown_disabled', models.BooleanField(db_index=True, default=False, verbose_name='关机计划关闭')),
                ('risk_unbound_user', models.BooleanField(db_index=True, default=False, verbose_name='未绑定用户')),
                ('risk_unbound_group', models.BooleanField(db_index=True, default=False, verbose_name='未绑定群组')),
                ('risk_auto_renew_off', models.BooleanField(db_index=True, default=False, verbose_name='续费关闭')),
                ('risk_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除/终止')),
                ('asset_updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='资产更新时间')),
                ('refreshed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='快照刷新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshot', to='cloud.cloudasset', verbose_name='云资产')),
                ('cloud_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_dashboard_snapshots', to='core.cloudaccountconfig', verbose_name='云账号')),
                ('telegram_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_dashboard_snapshots', to='bot.telegramgroupfilter', verbose_name='绑定群组')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_dashboard_snapshots', to='bot.telegramuser', verbose_name='绑定用户')),
            ],
            options={
                'verbose_name': '云资产列表快照',
                'verbose_name_plural': '云资产列表快照',
                'db_table': 'cloud_asset_dashboard_snapshot',
                'ordering': ['risk_rank', 'actual_expires_at', '-sort_order', '-asset_id'],
                'indexes': [models.Index(fields=['risk_account_disabled', 'risk_rank', 'actual_expires_at'], name='cad_risk_display_idx'), models.Index(fields=['group_user_key', 'risk_rank', 'actual_expires_at'], name='cad_group_user_idx'), models.Index(fields=['group_telegram_key', 'risk_rank', 'actual_expires_at'], name='cad_group_tg_idx'), models.Index(fields=['provider', 'cloud_account', 'region_code', 'status'], name='cad_provider_scope_idx'), models.Index(fields=['risk_unattached_ip', 'is_active', 'status'], name='idx_cad_display_state')],
            },
        ),
        migrations.CreateModel(
            name='CloudAssetSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='运行ID')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('succeeded', '已完成'), ('partial', '部分完成'), ('failed', '失败')], db_index=True, default='queued', max_length=32, verbose_name='状态')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('providers', models.JSONField(blank=True, default=list, verbose_name='云厂商范围')),
                ('account_ids', models.JSONField(blank=True, default=list, verbose_name='账号范围')),
                ('asset_ids', models.JSONField(blank=True, default=list, verbose_name='资产范围')),
                ('scope', models.JSONField(blank=True, default=dict, verbose_name='同步范围')),
                ('progress_current', models.PositiveIntegerField(default=0, verbose_name='已完成任务数')),
                ('progress_total', models.PositiveIntegerField(default=0, verbose_name='总任务数')),
                ('current_task', models.CharField(blank=True, default='', max_length=255, verbose_name='当前任务')),
                ('logs', models.JSONField(blank=True, default=list, verbose_name='日志摘要')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='警告')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='错误')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='结果载荷')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_sync_jobs', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '云资产同步任务',
                'verbose_name_plural': '云资产同步任务',
                'db_table': 'cloud_asset_sync_job',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_cloud_sync_job_status'), models.Index(fields=['requested_by', 'created_at'], name='idx_cloud_sync_job_user')],
            },
        ),
    ]
