# Generated by Django 5.2.13 on 2026-06-01 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0041_dashboard_snapshot_jobs_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAssetSyncJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.BigIntegerField(db_index=True, verbose_name='同步任务ID')),
                ('event_type', models.CharField(choices=[('queued', '入队'), ('claimed', '领取'), ('status', '状态'), ('progress', '进度'), ('task', '任务'), ('warning', '警告'), ('error', '错误'), ('log', '日志'), ('cancel', '取消'), ('retry', '重试'), ('heartbeat', '心跳')], db_index=True, max_length=32, verbose_name='事件类型')),
                ('status_from', models.CharField(blank=True, default='', max_length=32, verbose_name='原状态')),
                ('status_to', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='新状态')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='事件摘要')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件载荷')),
                ('worker_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Worker ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '云资产同步任务事件',
                'verbose_name_plural': '云资产同步任务事件',
                'db_table': 'cloud_asset_sync_job_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cloudassetsyncjob',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='取消请求时间'),
        ),
        migrations.AddField(
            model_name='cloudassetsyncjob',
            name='cancel_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_cloud_asset_sync_jobs', to=settings.AUTH_USER_MODEL, verbose_name='取消发起人'),
        ),
        migrations.AddField(
            model_name='cloudassetsyncjob',
            name='worker_heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Worker 心跳时间'),
        ),
        migrations.AddField(
            model_name='cloudassetsyncjob',
            name='worker_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Worker ID'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='status',
            field=models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('succeeded', '已完成'), ('partial', '部分完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='queued', max_length=32, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='cloudassetsyncjob',
            index=models.Index(fields=['status', 'worker_heartbeat_at'], name='idx_cloud_sync_job_heartbeat'),
        ),
        migrations.AddField(
            model_name='cloudassetsyncjobevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_sync_job_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddIndex(
            model_name='cloudassetsyncjobevent',
            index=models.Index(fields=['job_id', 'created_at'], name='idx_cloud_sync_event_job_time'),
        ),
        migrations.AddIndex(
            model_name='cloudassetsyncjobevent',
            index=models.Index(fields=['event_type', 'created_at'], name='idx_cloud_sync_event_type_time'),
        ),
        migrations.AddIndex(
            model_name='cloudassetsyncjobevent',
            index=models.Index(fields=['worker_id', 'created_at'], name='idx_cloud_sync_event_worker'),
        ),
    ]
