# Generated by Django 5.2.13 on 2026-06-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_telegramgroupfilter_archived'),
        ('cloud', '0045_delete_plan_snapshot_tables'),
        ('core', '0011_trongrid_api_key_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudassetdashboardsnapshot',
            options={'ordering': ['risk_rank', '-sort_order', '-asset_id'], 'verbose_name': '云资产列表快照', 'verbose_name_plural': '云资产列表快照'},
        ),
        migrations.RemoveIndex(
            model_name='cloudassetdashboardsnapshot',
            name='cad_risk_display_idx',
        ),
        migrations.RemoveIndex(
            model_name='cloudassetdashboardsnapshot',
            name='cad_group_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='cloudassetdashboardsnapshot',
            name='cad_group_tg_idx',
        ),
        migrations.RemoveField(
            model_name='cloudassetdashboardsnapshot',
            name='actual_expires_at',
        ),
        migrations.RemoveField(
            model_name='cloudautorenewpatrollog',
            name='service_expires_at',
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_account_disabled', 'risk_rank', '-sort_order'], name='cad_risk_display_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['group_user_key', 'risk_rank', '-sort_order'], name='cad_group_user_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['group_telegram_key', 'risk_rank', '-sort_order'], name='cad_group_tg_idx'),
        ),
    ]
