# Generated by Django 5.2.13 on 2026-06-02 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_telegramgroupfilter_archived'),
        ('cloud', '0046_remove_derived_expiry_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudLifecycleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=191, unique=True, verbose_name='来源唯一键')),
                ('task_type', models.CharField(choices=[('suspend', '计划关机'), ('delete', '计划删机'), ('recycle', '固定IP回收'), ('migration_delete', '迁移旧机删除'), ('orphan_asset_delete', '无订单资产删除'), ('unattached_ip_delete', '未附加固定IP删除')], db_index=True, max_length=64, verbose_name='任务类型')),
                ('source_kind', models.CharField(choices=[('order', '订单'), ('asset', '资产')], db_index=True, max_length=32, verbose_name='来源类型')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='计划执行时间')),
                ('basis_actual_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='依据资产到期时间')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('claimed', '执行中'), ('done', '已完成'), ('skipped', '已跳过'), ('failed', '执行失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=32, verbose_name='状态')),
                ('claim_token', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='认领令牌')),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='认领时间')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('last_error', models.TextField(blank=True, verbose_name='最后错误')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='计划载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_tasks', to='cloud.cloudasset', verbose_name='关联资产')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_tasks', to='cloud.cloudserverorder', verbose_name='关联订单')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_lifecycle_tasks', to='bot.telegramuser', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '生命周期任务',
                'verbose_name_plural': '生命周期任务',
                'db_table': 'cloud_lifecycle_task',
                'ordering': ['scheduled_at', 'id'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='clt_status_due_idx'), models.Index(fields=['task_type', 'status', 'scheduled_at'], name='clt_type_status_due_idx'), models.Index(fields=['source_kind', 'order', 'task_type'], name='clt_order_task_idx'), models.Index(fields=['source_kind', 'asset', 'task_type'], name='clt_asset_task_idx')],
            },
        ),
        migrations.CreateModel(
            name='CloudNoticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=191, unique=True, verbose_name='来源唯一键')),
                ('notice_type', models.CharField(choices=[('renew_notice', '到期提醒'), ('auto_renew_notice', '自动续费预提醒'), ('delete_notice', '删机提醒'), ('recycle_notice', 'IP回收提醒')], db_index=True, max_length=64, verbose_name='通知类型')),
                ('target_chat_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='目标群组/会话ID')),
                ('notice_at', models.DateTimeField(db_index=True, verbose_name='计划通知时间')),
                ('basis_actual_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='依据资产到期时间')),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=191, verbose_name='通知批次')),
                ('status', models.CharField(choices=[('pending', '待通知'), ('claimed', '通知中'), ('sent', '已通知'), ('failed', '通知失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=32, verbose_name='状态')),
                ('claim_token', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='认领令牌')),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='认领时间')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('last_error', models.TextField(blank=True, verbose_name='最后错误')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='通知成功时间')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='计划载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_tasks', to='cloud.cloudasset', verbose_name='关联资产')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_tasks', to='cloud.cloudserverorder', verbose_name='关联订单')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_notice_tasks', to='bot.telegramuser', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '通知任务',
                'verbose_name_plural': '通知任务',
                'db_table': 'cloud_notice_task',
                'ordering': ['notice_at', 'id'],
                'indexes': [models.Index(fields=['status', 'notice_at'], name='cnt_status_due_idx'), models.Index(fields=['notice_type', 'status', 'notice_at'], name='cnt_type_status_due_idx'), models.Index(fields=['order', 'notice_type'], name='cnt_order_type_idx'), models.Index(fields=['user', 'notice_type', 'status'], name='cnt_user_type_status_idx')],
            },
        ),
    ]
