# Generated by Django 5.2.13 on 2026-06-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0048_cloudasset_shutdown_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudserverorder',
            name='mtproxy_port',
            field=models.IntegerField(default=443, verbose_name='MTProxy端口'),
        ),
    ]
