# Generated by Django 5.2.13 on 2026-06-03 01:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_adminreplylink_table_comment_and_more'),
        ('cloud', '0049_alter_cloudserverorder_mtproxy_port'),
        ('core', '0013_alter_cloudaccountconfig_table_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='addressmonitor',
            table_comment='链上地址监控配置表',
        ),
        migrations.AlterModelTableComment(
            name='cloudasset',
            table_comment='云资源事实表',
        ),
        migrations.AlterModelTableComment(
            name='cloudassetdashboardsnapshot',
            table_comment='云资产后台列表快照表，不保存资产到期事实',
        ),
        migrations.AlterModelTableComment(
            name='cloudassetsyncjob',
            table_comment='云资产同步任务主表',
        ),
        migrations.AlterModelTableComment(
            name='cloudassetsyncjobevent',
            table_comment='云资产同步任务事件表',
        ),
        migrations.AlterModelTableComment(
            name='cloudautorenewpatrollog',
            table_comment='云服务器自动续费巡检执行日志表',
        ),
        migrations.AlterModelTableComment(
            name='cloudautorenewretrytask',
            table_comment='云服务器自动续费失败重试任务表',
        ),
        migrations.AlterModelTableComment(
            name='cloudiplog',
            table_comment='云资产公网IP变更和回收日志表',
        ),
        migrations.AlterModelTableComment(
            name='cloudlifecycleplannote',
            table_comment='生命周期删除计划人工备注表',
        ),
        migrations.AlterModelTableComment(
            name='cloudlifecycletask',
            table_comment='云资产生命周期执行任务表',
        ),
        migrations.AlterModelTableComment(
            name='cloudnoticetask',
            table_comment='云资产用户通知任务表',
        ),
        migrations.AlterModelTableComment(
            name='cloudserverorder',
            table_comment='云服务器订单和操作流程上下文表',
        ),
        migrations.AlterModelTableComment(
            name='cloudserverplan',
            table_comment='云服务器销售套餐配置表',
        ),
        migrations.AlterModelTableComment(
            name='cloudusernoticelog',
            table_comment='云服务器用户通知发送日志表',
        ),
        migrations.AlterModelTableComment(
            name='dailyaddressstat',
            table_comment='链上地址每日收支统计表',
        ),
        migrations.AlterModelTableComment(
            name='resourcesnapshot',
            table_comment='链上地址资源快照表',
        ),
        migrations.AlterModelTableComment(
            name='serverprice',
            table_comment='云厂商服务器规格和销售价格配置表',
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='address',
            field=models.CharField(db_comment='监控地址', db_index=True, max_length=191, verbose_name='监控地址'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='bandwidth_threshold',
            field=models.BigIntegerField(db_comment='带宽增加阈值', default=1, verbose_name='带宽增加阈值'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='daily_expense',
            field=models.DecimalField(db_comment='今日支出', decimal_places=6, default=0, max_digits=18, verbose_name='今日支出'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='daily_expense_currency',
            field=models.CharField(db_comment='支出币种', default='USDT', max_length=32, verbose_name='支出币种'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='daily_income',
            field=models.DecimalField(db_comment='今日收入', decimal_places=6, default=0, max_digits=18, verbose_name='今日收入'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='daily_income_currency',
            field=models.CharField(db_comment='收入币种', default='USDT', max_length=32, verbose_name='收入币种'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='energy_threshold',
            field=models.BigIntegerField(db_comment='能量增加阈值', default=1, verbose_name='能量增加阈值'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='is_active',
            field=models.BooleanField(db_comment='启用', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='last_bandwidth',
            field=models.BigIntegerField(db_comment='上次可用带宽', default=0, verbose_name='上次可用带宽'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='last_energy',
            field=models.BigIntegerField(db_comment='上次可用能量', default=0, verbose_name='上次可用能量'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='monitor_resources',
            field=models.BooleanField(db_comment='监控资源', default=False, verbose_name='监控资源'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='monitor_transfers',
            field=models.BooleanField(db_comment='监控转账', default=True, verbose_name='监控转账'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='remark',
            field=models.TextField(blank=True, db_comment='备注', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='resource_checked_at',
            field=models.DateTimeField(blank=True, db_comment='资源检查时间', null=True, verbose_name='资源检查时间'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='stats_date',
            field=models.CharField(blank=True, db_comment='统计日期', max_length=32, null=True, verbose_name='统计日期'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='trx_threshold',
            field=models.DecimalField(db_comment='TRX阈值', decimal_places=6, default=1, max_digits=18, verbose_name='TRX阈值'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='usdt_threshold',
            field=models.DecimalField(db_comment='USDT阈值', decimal_places=6, default=1, max_digits=18, verbose_name='USDT阈值'),
        ),
        migrations.AlterField(
            model_name='addressmonitor',
            name='user',
            field=models.ForeignKey(db_comment='用户', on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='account_label',
            field=models.CharField(blank=True, db_comment='账户/来源标识', db_index=True, max_length=191, null=True, verbose_name='账户/来源标识'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='actual_expires_at',
            field=models.DateTimeField(blank=True, db_comment='云资产唯一真实到期事实，生命周期计划和续费判断以此字段为准', db_index=True, null=True, verbose_name='实际到期时间'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='asset_name',
            field=models.CharField(blank=True, db_comment='资产名称', db_index=True, max_length=191, null=True, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='cloud_account',
            field=models.ForeignKey(blank=True, db_comment='云账号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_assets', to='core.cloudaccountconfig', verbose_name='云账号'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='currency',
            field=models.CharField(db_comment='币种', default='USDT', max_length=32, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='instance_id',
            field=models.CharField(blank=True, db_comment='实例ID', db_index=True, max_length=191, null=True, verbose_name='实例ID'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='is_active',
            field=models.BooleanField(db_comment='有效', db_index=True, default=True, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='kind',
            field=models.CharField(choices=[('server', '云服务器'), ('mtproxy', 'MTProxy代理')], db_comment='资产类型', db_index=True, max_length=32, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='login_password',
            field=models.CharField(blank=True, db_comment='登录密码', max_length=191, null=True, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='login_user',
            field=models.CharField(blank=True, db_comment='登录账号', max_length=64, null=True, verbose_name='登录账号'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='mtproxy_host',
            field=models.CharField(blank=True, db_comment='MTProxy主机', max_length=191, null=True, verbose_name='MTProxy主机'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='mtproxy_link',
            field=models.TextField(blank=True, db_comment='MTProxy链接', null=True, verbose_name='MTProxy链接'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='mtproxy_port',
            field=models.IntegerField(blank=True, db_comment='MTProxy端口', null=True, verbose_name='MTProxy端口'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='mtproxy_secret',
            field=models.CharField(blank=True, db_comment='MTProxy密钥', max_length=191, null=True, verbose_name='MTProxy密钥'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='note',
            field=models.TextField(blank=True, db_comment='备注', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='关联订单', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.cloudserverorder', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='previous_public_ip',
            field=models.CharField(blank=True, db_comment='历史公网IP', max_length=128, null=True, verbose_name='历史公网IP'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='price',
            field=models.DecimalField(blank=True, db_comment='价格', decimal_places=6, max_digits=18, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='provider',
            field=models.CharField(blank=True, db_comment='云厂商', db_index=True, max_length=32, null=True, verbose_name='云厂商'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='provider_resource_id',
            field=models.CharField(blank=True, db_comment='云资源ID', db_index=True, max_length=191, null=True, verbose_name='云资源ID'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='provider_status',
            field=models.CharField(blank=True, db_comment='云厂商原始状态', db_index=True, max_length=64, null=True, verbose_name='云厂商原始状态'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='proxy_links',
            field=models.JSONField(blank=True, db_comment='代理链路', default=list, verbose_name='代理链路'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='public_ip',
            field=models.CharField(blank=True, db_comment='公网IP', db_index=True, max_length=128, null=True, verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='region_code',
            field=models.CharField(blank=True, db_comment='地区代码', db_index=True, max_length=64, null=True, verbose_name='地区代码'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='region_name',
            field=models.CharField(blank=True, db_comment='地区名称', max_length=128, null=True, verbose_name='地区名称'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='shutdown_enabled',
            field=models.BooleanField(db_comment='关机计划启用', db_index=True, default=True, verbose_name='关机计划启用'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='sort_order',
            field=models.IntegerField(db_comment='排序', db_index=True, default=99, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='source',
            field=models.CharField(choices=[('aliyun', '阿里云自动同步'), ('aws_manual', 'AWS手工录入'), ('aws_sync', 'AWS脚本同步'), ('order', '订单创建')], db_comment='来源', db_index=True, default='order', max_length=32, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('pending', '等待中'), ('starting', '启动中'), ('stopping', '停止中'), ('stopped', '已关机'), ('suspended', '已停机'), ('terminating', '终止中'), ('terminated', '已终止'), ('deleting', '删除中'), ('deleted', '已删除'), ('expired', '已过期'), ('expired_grace', '到期延停'), ('unknown', '未知状态')], db_comment='状态', db_index=True, default='running', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='sync_state',
            field=models.JSONField(blank=True, db_comment='同步状态', default=dict, verbose_name='同步状态'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='telegram_group',
            field=models.ForeignKey(blank=True, db_comment='绑定群组', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramgroupfilter', verbose_name='绑定群组'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='绑定用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser', verbose_name='绑定用户'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='account_label',
            field=models.CharField(blank=True, db_comment='账户/来源标识', db_index=True, max_length=191, null=True, verbose_name='账户/来源标识'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='asset',
            field=models.OneToOneField(db_comment='云资产', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshot', to='cloud.cloudasset', verbose_name='云资产'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='asset_updated_at',
            field=models.DateTimeField(blank=True, db_comment='资产更新时间', db_index=True, null=True, verbose_name='资产更新时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='cloud_account',
            field=models.ForeignKey(blank=True, db_comment='云账号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_dashboard_snapshots', to='core.cloudaccountconfig', verbose_name='云账号'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='group_telegram_key',
            field=models.CharField(db_comment='群组分组键', db_index=True, max_length=191, verbose_name='群组分组键'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='group_telegram_label',
            field=models.CharField(blank=True, db_comment='群组分组标签', max_length=191, verbose_name='群组分组标签'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='group_user_key',
            field=models.CharField(db_comment='用户分组键', db_index=True, max_length=191, verbose_name='用户分组键'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='group_user_label',
            field=models.CharField(blank=True, db_comment='用户分组标签', max_length=191, verbose_name='用户分组标签'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='is_active',
            field=models.BooleanField(db_comment='是否活跃', db_index=True, default=True, verbose_name='是否活跃'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='payload',
            field=models.JSONField(blank=True, db_comment='列表载荷', default=dict, verbose_name='列表载荷'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='provider',
            field=models.CharField(blank=True, db_comment='云厂商', db_index=True, max_length=32, null=True, verbose_name='云厂商'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='public_ip',
            field=models.CharField(blank=True, db_comment='公网IP', db_index=True, max_length=128, null=True, verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='refreshed_at',
            field=models.DateTimeField(auto_now=True, db_comment='快照刷新时间', db_index=True, verbose_name='快照刷新时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='region_code',
            field=models.CharField(blank=True, db_comment='地区代码', db_index=True, max_length=64, null=True, verbose_name='地区代码'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_abnormal',
            field=models.BooleanField(db_comment='异常/待确认', db_index=True, default=False, verbose_name='异常/待确认'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_account_disabled',
            field=models.BooleanField(db_comment='云账号已停用', db_index=True, default=False, verbose_name='云账号已停用'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_auto_renew_off',
            field=models.BooleanField(db_comment='续费关闭', db_index=True, default=False, verbose_name='续费关闭'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_deleted',
            field=models.BooleanField(db_comment='已删除/终止', db_index=True, default=False, verbose_name='已删除/终止'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_due_soon',
            field=models.BooleanField(db_comment='即将到期', db_index=True, default=False, verbose_name='即将到期'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_expired',
            field=models.BooleanField(db_comment='已过期', db_index=True, default=False, verbose_name='已过期'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_normal',
            field=models.BooleanField(db_comment='运行中', db_index=True, default=False, verbose_name='运行中'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_rank',
            field=models.IntegerField(db_comment='风险排序', db_index=True, default=99, verbose_name='风险排序'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_shutdown_disabled',
            field=models.BooleanField(db_comment='关机计划关闭', db_index=True, default=False, verbose_name='关机计划关闭'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_status',
            field=models.CharField(db_comment='风险状态', db_index=True, default='other', max_length=64, verbose_name='风险状态'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_statuses',
            field=models.JSONField(blank=True, db_comment='风险状态集合', default=list, verbose_name='风险状态集合'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_unattached_ip',
            field=models.BooleanField(db_comment='未附加固定IP', db_index=True, default=False, verbose_name='未附加固定IP'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_unbound_group',
            field=models.BooleanField(db_comment='未绑定群组', db_index=True, default=False, verbose_name='未绑定群组'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='risk_unbound_user',
            field=models.BooleanField(db_comment='未绑定用户', db_index=True, default=False, verbose_name='未绑定用户'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='search_text',
            field=models.TextField(blank=True, db_comment='搜索文本', verbose_name='搜索文本'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='sort_order',
            field=models.IntegerField(db_comment='排序', db_index=True, default=99, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='status',
            field=models.CharField(blank=True, db_comment='状态', db_index=True, max_length=32, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='telegram_group',
            field=models.ForeignKey(blank=True, db_comment='绑定群组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_dashboard_snapshots', to='bot.telegramgroupfilter', verbose_name='绑定群组'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='tg_user_id',
            field=models.BigIntegerField(blank=True, db_comment='Telegram 用户ID', db_index=True, null=True, verbose_name='Telegram 用户ID'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='绑定用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_dashboard_snapshots', to='bot.telegramuser', verbose_name='绑定用户'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='account_ids',
            field=models.JSONField(blank=True, db_comment='账号范围', default=list, verbose_name='账号范围'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='asset_ids',
            field=models.JSONField(blank=True, db_comment='资产范围', default=list, verbose_name='资产范围'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, db_comment='取消请求时间', db_index=True, null=True, verbose_name='取消请求时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='cancel_requested_by',
            field=models.ForeignKey(blank=True, db_comment='取消发起人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_cloud_asset_sync_jobs', to=settings.AUTH_USER_MODEL, verbose_name='取消发起人'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='current_task',
            field=models.CharField(blank=True, db_comment='当前任务', default='', max_length=255, verbose_name='当前任务'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='errors',
            field=models.JSONField(blank=True, db_comment='错误', default=list, verbose_name='错误'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_comment='结束时间', db_index=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='logs',
            field=models.JSONField(blank=True, db_comment='日志摘要', default=list, verbose_name='日志摘要'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='progress_current',
            field=models.PositiveIntegerField(db_comment='已完成任务数', default=0, verbose_name='已完成任务数'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='progress_total',
            field=models.PositiveIntegerField(db_comment='总任务数', default=0, verbose_name='总任务数'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='providers',
            field=models.JSONField(blank=True, db_comment='云厂商范围', default=list, verbose_name='云厂商范围'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='request_payload',
            field=models.JSONField(blank=True, db_comment='请求参数', default=dict, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='requested_by',
            field=models.ForeignKey(blank=True, db_comment='发起人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_sync_jobs', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='result_payload',
            field=models.JSONField(blank=True, db_comment='结果载荷', default=dict, verbose_name='结果载荷'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='run_id',
            field=models.CharField(db_comment='运行ID', db_index=True, max_length=32, unique=True, verbose_name='运行ID'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='scope',
            field=models.JSONField(blank=True, db_comment='同步范围', default=dict, verbose_name='同步范围'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='started_at',
            field=models.DateTimeField(blank=True, db_comment='开始时间', db_index=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='status',
            field=models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('succeeded', '已完成'), ('partial', '部分完成'), ('failed', '失败'), ('cancelled', '已取消')], db_comment='状态', db_index=True, default='queued', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='warnings',
            field=models.JSONField(blank=True, db_comment='警告', default=list, verbose_name='警告'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='worker_heartbeat_at',
            field=models.DateTimeField(blank=True, db_comment='Worker 心跳时间', db_index=True, null=True, verbose_name='Worker 心跳时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='worker_id',
            field=models.CharField(blank=True, db_comment='Worker ID', db_index=True, default='', max_length=64, verbose_name='Worker ID'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='actor',
            field=models.ForeignKey(blank=True, db_comment='操作人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_asset_sync_job_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='event_type',
            field=models.CharField(choices=[('queued', '入队'), ('claimed', '领取'), ('status', '状态'), ('progress', '进度'), ('task', '任务'), ('warning', '警告'), ('error', '错误'), ('log', '日志'), ('cancel', '取消'), ('retry', '重试'), ('heartbeat', '心跳')], db_comment='事件类型', db_index=True, max_length=32, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='job_id',
            field=models.BigIntegerField(db_comment='同步任务ID', db_index=True, verbose_name='同步任务ID'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='message',
            field=models.CharField(blank=True, db_comment='事件摘要', default='', max_length=255, verbose_name='事件摘要'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='payload',
            field=models.JSONField(blank=True, db_comment='事件载荷', default=dict, verbose_name='事件载荷'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='status_from',
            field=models.CharField(blank=True, db_comment='原状态', default='', max_length=32, verbose_name='原状态'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='status_to',
            field=models.CharField(blank=True, db_comment='新状态', db_index=True, default='', max_length=32, verbose_name='新状态'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='worker_id',
            field=models.CharField(blank=True, db_comment='Worker ID', db_index=True, default='', max_length=64, verbose_name='Worker ID'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='balance_after',
            field=models.DecimalField(blank=True, db_comment='余额变更后', decimal_places=6, max_digits=18, null=True, verbose_name='余额变更后'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='balance_before',
            field=models.DecimalField(blank=True, db_comment='余额变更前', decimal_places=6, max_digits=18, null=True, verbose_name='余额变更前'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='balance_change',
            field=models.DecimalField(blank=True, db_comment='余额变化', decimal_places=6, max_digits=18, null=True, verbose_name='余额变化'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='batch_id',
            field=models.CharField(db_comment='巡检批次', db_index=True, max_length=64, verbose_name='巡检批次'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='completed_order_id',
            field=models.BigIntegerField(blank=True, db_comment='续费后订单ID', db_index=True, null=True, verbose_name='续费后订单ID'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='completed_order_no',
            field=models.CharField(blank=True, db_comment='续费后订单号', db_index=True, max_length=191, null=True, verbose_name='续费后订单号'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='currency',
            field=models.CharField(db_comment='币种', default='USDT', max_length=32, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='执行时间', db_index=True, verbose_name='执行时间'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='failure_reason',
            field=models.TextField(blank=True, db_comment='失败原因', null=True, verbose_name='失败原因'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='ip',
            field=models.CharField(db_comment='公网IP', db_index=True, max_length=128, verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='is_success',
            field=models.BooleanField(db_comment='是否成功', db_index=True, default=False, verbose_name='是否成功'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='云服务器订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_renew_patrol_logs', to='cloud.cloudserverorder', verbose_name='云服务器订单'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='order_no',
            field=models.CharField(db_comment='订单号', db_index=True, max_length=191, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='provider',
            field=models.CharField(blank=True, db_comment='云厂商', db_index=True, max_length=32, null=True, verbose_name='云厂商'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='tg_user_id',
            field=models.BigIntegerField(blank=True, db_comment='Telegram ID', db_index=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_renew_patrol_logs', to='bot.telegramuser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='user_display_name',
            field=models.CharField(blank=True, db_comment='用户显示名', max_length=191, null=True, verbose_name='用户显示名'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='username_label',
            field=models.CharField(blank=True, db_comment='用户名', max_length=191, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='attempts',
            field=models.PositiveIntegerField(db_comment='重试次数', default=0, verbose_name='重试次数'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_comment='取消时间', null=True, verbose_name='取消时间'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='failure_reason',
            field=models.TextField(blank=True, db_comment='失败原因', null=True, verbose_name='失败原因'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='ip',
            field=models.CharField(blank=True, db_comment='公网IP', db_index=True, max_length=128, null=True, verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, db_comment='最后检查时间', null=True, verbose_name='最后检查时间'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='last_error',
            field=models.TextField(blank=True, db_comment='最后错误', null=True, verbose_name='最后错误'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='next_check_at',
            field=models.DateTimeField(db_comment='自动续费失败后的下一次重试检查时间', db_index=True, verbose_name='下次检查时间'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='order',
            field=models.ForeignKey(db_comment='云服务器订单', on_delete=django.db.models.deletion.CASCADE, related_name='auto_renew_retry_tasks', to='cloud.cloudserverorder', verbose_name='云服务器订单'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='order_no',
            field=models.CharField(db_comment='订单号', db_index=True, max_length=191, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='status',
            field=models.CharField(choices=[('pending', '待重试'), ('succeeded', '已成功'), ('cancelled', '已取消'), ('failed', '重试失败')], db_comment='状态', db_index=True, default='pending', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='succeeded_at',
            field=models.DateTimeField(blank=True, db_comment='成功时间', null=True, verbose_name='成功时间'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_renew_retry_tasks', to='bot.telegramuser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='asset',
            field=models.ForeignKey(blank=True, db_comment='关联资产', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_logs', to='cloud.cloudasset', verbose_name='关联资产'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='asset_name',
            field=models.CharField(blank=True, db_comment='资产名称', db_index=True, max_length=191, null=True, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='记录时间', db_index=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='event_type',
            field=models.CharField(choices=[('created', '创建分配'), ('changed', 'IP变更'), ('renewed', '续费'), ('expired', '到期'), ('suspended', '延停'), ('deleted', '删除'), ('recycled', '回收')], db_comment='事件类型', db_index=True, max_length=32, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='instance_id',
            field=models.CharField(blank=True, db_comment='实例ID', db_index=True, max_length=191, null=True, verbose_name='实例ID'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='note',
            field=models.TextField(blank=True, db_comment='说明', null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='关联订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_logs', to='cloud.cloudserverorder', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='order_no',
            field=models.CharField(blank=True, db_comment='订单号', db_index=True, max_length=191, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='previous_public_ip',
            field=models.CharField(blank=True, db_comment='上一个IP', db_index=True, max_length=128, null=True, verbose_name='上一个IP'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='provider',
            field=models.CharField(blank=True, db_comment='云厂商', db_index=True, max_length=32, null=True, verbose_name='云厂商'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='provider_resource_id',
            field=models.CharField(blank=True, db_comment='云资源ID', db_index=True, max_length=191, null=True, verbose_name='云资源ID'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='public_ip',
            field=models.CharField(blank=True, db_comment='当前IP', db_index=True, max_length=128, null=True, verbose_name='当前IP'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='region_code',
            field=models.CharField(blank=True, db_comment='地区代码', db_index=True, max_length=64, null=True, verbose_name='地区代码'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='region_name',
            field=models.CharField(blank=True, db_comment='地区名称', max_length=128, null=True, verbose_name='地区名称'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='关联用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_ip_logs', to='bot.telegramuser', verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycleplannote',
            name='asset',
            field=models.ForeignKey(blank=True, db_comment='关联资产', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_plan_notes', to='cloud.cloudasset', verbose_name='关联资产'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycleplannote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycleplannote',
            name='created_by',
            field=models.ForeignKey(blank=True, db_comment='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cloud_lifecycle_plan_notes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycleplannote',
            name='note',
            field=models.TextField(blank=True, db_comment='备注', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycleplannote',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='关联订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_plan_notes', to='cloud.cloudserverorder', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycleplannote',
            name='plan_kind',
            field=models.CharField(choices=[('shutdown_order', '订单删机计划'), ('orphan_asset_delete', '无订单资产删机计划'), ('unattached_ip_delete', '未附加固定IP删除计划')], db_comment='计划类型', db_index=True, max_length=64, verbose_name='计划类型'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycleplannote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycleplannote',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cloud_lifecycle_plan_notes', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='asset',
            field=models.ForeignKey(blank=True, db_comment='关联资产', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_tasks', to='cloud.cloudasset', verbose_name='关联资产'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='attempt_count',
            field=models.PositiveIntegerField(db_comment='尝试次数', default=0, verbose_name='尝试次数'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='basis_actual_expires_at',
            field=models.DateTimeField(blank=True, db_comment='生成任务时引用的CloudAsset.actual_expires_at快照', null=True, verbose_name='依据资产到期时间'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='claim_token',
            field=models.CharField(blank=True, db_comment='任务执行器认领令牌，用于并发执行隔离', db_index=True, max_length=64, verbose_name='认领令牌'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_comment='认领时间', db_index=True, null=True, verbose_name='认领时间'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_comment='完成时间', null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='last_error',
            field=models.TextField(blank=True, db_comment='最后错误', verbose_name='最后错误'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='last_run_at',
            field=models.DateTimeField(blank=True, db_comment='最后执行时间', null=True, verbose_name='最后执行时间'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='关联订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_tasks', to='cloud.cloudserverorder', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='payload',
            field=models.JSONField(blank=True, db_comment='计划载荷', default=dict, verbose_name='计划载荷'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='scheduled_at',
            field=models.DateTimeField(db_comment='生命周期任务计划执行时间', db_index=True, verbose_name='计划执行时间'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='source_key',
            field=models.CharField(db_comment='生命周期任务幂等来源唯一键', max_length=191, unique=True, verbose_name='来源唯一键'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='source_kind',
            field=models.CharField(choices=[('order', '订单'), ('asset', '资产')], db_comment='来源类型', db_index=True, max_length=32, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('claimed', '执行中'), ('done', '已完成'), ('skipped', '已跳过'), ('failed', '执行失败'), ('cancelled', '已取消')], db_comment='状态', db_index=True, default='pending', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='task_type',
            field=models.CharField(choices=[('suspend', '计划关机'), ('delete', '计划删机'), ('recycle', '固定IP回收'), ('migration_delete', '迁移旧机删除'), ('orphan_asset_delete', '无订单资产删除'), ('unattached_ip_delete', '未附加固定IP删除')], db_comment='任务类型', db_index=True, max_length=64, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='关联用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_lifecycle_tasks', to='bot.telegramuser', verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='asset',
            field=models.ForeignKey(blank=True, db_comment='关联资产', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_tasks', to='cloud.cloudasset', verbose_name='关联资产'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='attempt_count',
            field=models.PositiveIntegerField(db_comment='尝试次数', default=0, verbose_name='尝试次数'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='basis_actual_expires_at',
            field=models.DateTimeField(blank=True, db_comment='生成通知时引用的CloudAsset.actual_expires_at快照', null=True, verbose_name='依据资产到期时间'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='batch_id',
            field=models.CharField(blank=True, db_comment='通知批次', db_index=True, max_length=191, verbose_name='通知批次'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='claim_token',
            field=models.CharField(blank=True, db_comment='通知执行器认领令牌，用于并发发送隔离', db_index=True, max_length=64, verbose_name='认领令牌'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_comment='认领时间', db_index=True, null=True, verbose_name='认领时间'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='last_error',
            field=models.TextField(blank=True, db_comment='最后错误', verbose_name='最后错误'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='last_run_at',
            field=models.DateTimeField(blank=True, db_comment='最后执行时间', null=True, verbose_name='最后执行时间'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='notice_at',
            field=models.DateTimeField(db_comment='通知任务计划发送时间', db_index=True, verbose_name='计划通知时间'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='notice_type',
            field=models.CharField(choices=[('renew_notice', '到期提醒'), ('auto_renew_notice', '自动续费预提醒'), ('delete_notice', '删机提醒'), ('recycle_notice', 'IP回收提醒')], db_comment='通知类型', db_index=True, max_length=64, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='关联订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_tasks', to='cloud.cloudserverorder', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='payload',
            field=models.JSONField(blank=True, db_comment='计划载荷', default=dict, verbose_name='计划载荷'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_comment='通知成功时间', null=True, verbose_name='通知成功时间'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='source_key',
            field=models.CharField(db_comment='通知任务幂等来源唯一键', max_length=191, unique=True, verbose_name='来源唯一键'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='status',
            field=models.CharField(choices=[('pending', '待通知'), ('claimed', '通知中'), ('sent', '已通知'), ('failed', '通知失败'), ('cancelled', '已取消')], db_comment='状态', db_index=True, default='pending', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='target_chat_id',
            field=models.BigIntegerField(blank=True, db_comment='目标群组/会话ID', db_index=True, null=True, verbose_name='目标群组/会话ID'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='关联用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_notice_tasks', to='bot.telegramuser', verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='account_label',
            field=models.CharField(blank=True, db_comment='账户/来源标识', db_index=True, max_length=191, null=True, verbose_name='账户/来源标识'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='auto_renew_enabled',
            field=models.BooleanField(db_comment='自动续费', db_index=True, default=False, verbose_name='自动续费'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='auto_renew_failure_notice_sent_at',
            field=models.DateTimeField(blank=True, db_comment='自动续费失败通知发送时间', null=True, verbose_name='自动续费失败通知发送时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='auto_renew_notice_sent_at',
            field=models.DateTimeField(blank=True, db_comment='自动续费预提醒发送时间', null=True, verbose_name='自动续费预提醒发送时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='cloud_account',
            field=models.ForeignKey(blank=True, db_comment='云账号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_orders', to='core.cloudaccountconfig', verbose_name='云账号'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='cloud_reminder_enabled',
            field=models.BooleanField(db_comment='到期提醒', db_index=True, default=True, verbose_name='到期提醒'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_comment='完成时间', null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('TRX', 'TRX')], db_comment='币种', db_index=True, default='USDT', max_length=32, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='delay_quota',
            field=models.IntegerField(db_comment='延期次数', default=0, verbose_name='延期次数'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='delete_at',
            field=models.DateTimeField(blank=True, db_comment='订单派生的计划删机流程时间，不作为资产到期事实', null=True, verbose_name='计划删机时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='delete_notice_sent_at',
            field=models.DateTimeField(blank=True, db_comment='删机提醒发送时间', null=True, verbose_name='删机提醒发送时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='delete_reminder_enabled',
            field=models.BooleanField(db_comment='删机提醒', db_index=True, default=True, verbose_name='删机提醒'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='expired_at',
            field=models.DateTimeField(blank=True, db_comment='过期时间', null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='image_name',
            field=models.CharField(db_comment='镜像', default='debian', max_length=128, verbose_name='镜像'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='instance_id',
            field=models.CharField(blank=True, db_comment='实例ID', max_length=191, null=True, verbose_name='实例ID'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='ip_change_quota',
            field=models.IntegerField(db_comment='剩余更换IP次数', default=1, verbose_name='剩余更换IP次数'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='ip_recycle_at',
            field=models.DateTimeField(blank=True, db_comment='订单派生的固定IP回收流程时间，不作为资产到期事实', null=True, verbose_name='IP保留到期时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='ip_recycle_reminder_enabled',
            field=models.BooleanField(db_comment='IP保留期提醒', db_index=True, default=True, verbose_name='IP保留期提醒'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, db_comment='最后续费时间', null=True, verbose_name='最后续费时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='last_user_id',
            field=models.BigIntegerField(blank=True, db_comment='最近绑定TG用户ID', db_index=True, null=True, verbose_name='最近绑定TG用户ID'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='lifecycle_days',
            field=models.IntegerField(db_comment='有效期天数', default=31, verbose_name='有效期天数'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='login_password',
            field=models.CharField(blank=True, db_comment='登录密码', max_length=191, null=True, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='login_user',
            field=models.CharField(blank=True, db_comment='登录账号', max_length=64, null=True, verbose_name='登录账号'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='migration_due_at',
            field=models.DateTimeField(blank=True, db_comment='订单迁移旧机处理截止时间，不作为资产到期事实', null=True, verbose_name='迁移截止时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='mtproxy_host',
            field=models.CharField(blank=True, db_comment='MTProxy主机', max_length=191, null=True, verbose_name='MTProxy主机'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='mtproxy_link',
            field=models.TextField(blank=True, db_comment='MTProxy链接', null=True, verbose_name='MTProxy链接'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='mtproxy_port',
            field=models.IntegerField(db_comment='MTProxy端口', default=443, verbose_name='MTProxy端口'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='mtproxy_secret',
            field=models.CharField(blank=True, db_comment='MTProxy密钥', max_length=191, null=True, verbose_name='MTProxy密钥'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='order_no',
            field=models.CharField(db_comment='云服务器订单唯一编号', db_index=True, max_length=191, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_comment='支付时间', null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='pay_amount',
            field=models.DecimalField(blank=True, db_comment='余额或链上支付的最终应付金额', decimal_places=9, max_digits=18, null=True, verbose_name='应付金额'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='pay_method',
            field=models.CharField(choices=[('address', '地址支付'), ('balance', '余额支付')], db_comment='支付方式', default='address', max_length=32, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='payer_address',
            field=models.CharField(blank=True, db_comment='链上付款地址', db_index=True, max_length=191, null=True, verbose_name='链上付款地址'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='plan',
            field=models.ForeignKey(db_comment='套餐', on_delete=django.db.models.deletion.PROTECT, to='cloud.cloudserverplan', verbose_name='套餐'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='plan_name',
            field=models.CharField(db_comment='套餐名称', max_length=191, verbose_name='套餐名称'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='previous_public_ip',
            field=models.CharField(blank=True, db_comment='历史公网IP', max_length=128, null=True, verbose_name='历史公网IP'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='provider',
            field=models.CharField(db_comment='云厂商', db_index=True, max_length=32, verbose_name='云厂商'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='provider_resource_id',
            field=models.CharField(blank=True, db_comment='云资源ID', max_length=191, null=True, verbose_name='云资源ID'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='provision_note',
            field=models.TextField(blank=True, db_comment='创建说明', null=True, verbose_name='创建说明'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='proxy_links',
            field=models.JSONField(blank=True, db_comment='代理链路', default=list, verbose_name='代理链路'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='public_ip',
            field=models.CharField(blank=True, db_comment='公网IP', db_index=True, max_length=128, null=True, verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='quantity',
            field=models.IntegerField(db_comment='购买数量', default=1, verbose_name='购买数量'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='receive_address',
            field=models.CharField(blank=True, db_comment='链上收款地址', db_index=True, max_length=191, null=True, verbose_name='链上收款地址'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='recycle_notice_sent_at',
            field=models.DateTimeField(blank=True, db_comment='删IP提醒发送时间', null=True, verbose_name='删IP提醒发送时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='region_code',
            field=models.CharField(db_comment='地区代码', db_index=True, max_length=64, verbose_name='地区代码'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='region_name',
            field=models.CharField(db_comment='地区名称', max_length=128, verbose_name='地区名称'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='renew_extension_days',
            field=models.IntegerField(db_comment='临时延期天数', default=0, verbose_name='临时延期天数'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='renew_grace_expires_at',
            field=models.DateTimeField(blank=True, db_comment='订单续费宽限流程时间，不作为资产到期事实', null=True, verbose_name='续费宽限到期时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='renew_notice_sent_at',
            field=models.DateTimeField(blank=True, db_comment='续费提醒发送时间', null=True, verbose_name='续费提醒发送时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='replacement_for',
            field=models.ForeignKey(blank=True, db_comment='替换来源订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_orders', to='cloud.cloudserverorder', verbose_name='替换来源订单'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='server_name',
            field=models.CharField(blank=True, db_comment='服务器名', db_index=True, max_length=191, null=True, verbose_name='服务器名'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='service_started_at',
            field=models.DateTimeField(blank=True, db_comment='订单服务流程开始时间，不作为资产到期事实', null=True, verbose_name='服务开始时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='static_ip_name',
            field=models.CharField(blank=True, db_comment='固定IP名称', max_length=191, null=True, verbose_name='固定IP名称'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('provisioning', '创建中'), ('completed', '已创建'), ('renew_pending', '待续费'), ('expiring', '即将到期'), ('suspended', '已关机'), ('deleting', '删除中'), ('deleted', '已删除'), ('failed', '创建失败'), ('cancelled', '已取消'), ('expired', '已过期')], db_comment='状态', db_index=True, default='pending', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='suspend_at',
            field=models.DateTimeField(blank=True, db_comment='订单派生的计划关机流程时间，不作为资产到期事实', null=True, verbose_name='计划关机时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='suspend_reminder_enabled',
            field=models.BooleanField(db_comment='停机提醒', db_index=True, default=True, verbose_name='停机提醒'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='total_amount',
            field=models.DecimalField(db_comment='总金额', decimal_places=6, max_digits=18, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='tx_hash',
            field=models.CharField(blank=True, db_comment='云服务器订单链上支付交易哈希', max_length=191, null=True, unique=True, verbose_name='交易哈希'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='user',
            field=models.ForeignKey(db_comment='用户', on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='bandwidth',
            field=models.CharField(blank=True, db_comment='带宽', max_length=64, null=True, verbose_name='带宽'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='config_id',
            field=models.CharField(blank=True, db_comment='配置ID', db_index=True, default='', max_length=64, verbose_name='配置ID'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='cost_price',
            field=models.DecimalField(db_comment='进货价', decimal_places=6, default=0, max_digits=18, verbose_name='进货价'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='cpu',
            field=models.CharField(blank=True, db_comment='CPU', max_length=64, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='currency',
            field=models.CharField(db_comment='币种', default='USDT', max_length=32, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='display_bandwidth',
            field=models.CharField(blank=True, db_comment='展示带宽', max_length=64, verbose_name='展示带宽'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='display_cpu',
            field=models.CharField(blank=True, db_comment='展示CPU', max_length=64, verbose_name='展示CPU'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='display_description',
            field=models.TextField(blank=True, db_comment='展示说明', verbose_name='展示说明'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='display_memory',
            field=models.CharField(blank=True, db_comment='展示内存', max_length=64, verbose_name='展示内存'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='display_plan_name',
            field=models.CharField(blank=True, db_comment='展示套餐名', max_length=191, verbose_name='展示套餐名'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='display_storage',
            field=models.CharField(blank=True, db_comment='展示存储', max_length=64, verbose_name='展示存储'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='is_active',
            field=models.BooleanField(db_comment='启用', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='memory',
            field=models.CharField(blank=True, db_comment='内存', max_length=64, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='plan_description',
            field=models.TextField(blank=True, db_comment='套餐描述', null=True, verbose_name='套餐描述'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='plan_name',
            field=models.CharField(db_comment='套餐名称', max_length=191, verbose_name='套餐名称'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='price',
            field=models.DecimalField(db_comment='出售价', decimal_places=6, max_digits=18, verbose_name='出售价'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='provider',
            field=models.CharField(choices=[('aws_lightsail', 'AWS 光帆服务器'), ('aliyun_simple', '阿里云轻量云')], db_comment='云厂商', db_index=True, max_length=32, verbose_name='云厂商'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='provider_plan_id',
            field=models.CharField(blank=True, db_comment='云厂商套餐ID', db_index=True, max_length=191, verbose_name='云厂商套餐ID'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='region_code',
            field=models.CharField(db_comment='地区代码', db_index=True, max_length=64, verbose_name='地区代码'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='region_name',
            field=models.CharField(db_comment='地区名称', max_length=128, verbose_name='地区名称'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='sort_order',
            field=models.IntegerField(db_comment='排序', default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='storage',
            field=models.CharField(blank=True, db_comment='存储', max_length=64, null=True, verbose_name='存储'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='batch_id',
            field=models.CharField(blank=True, db_comment='通知批次', db_index=True, default='', max_length=64, verbose_name='通知批次'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='记录时间', db_index=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='delivered',
            field=models.BooleanField(db_comment='是否送达', db_index=True, default=False, verbose_name='是否送达'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='event_type',
            field=models.CharField(db_comment='通知类型', db_index=True, max_length=64, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='extra',
            field=models.JSONField(blank=True, db_comment='额外信息', default=dict, verbose_name='额外信息'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='ip',
            field=models.CharField(blank=True, db_comment='IP', db_index=True, max_length=128, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='is_batch',
            field=models.BooleanField(db_comment='是否批量', db_index=True, default=False, verbose_name='是否批量'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='order',
            field=models.ForeignKey(blank=True, db_comment='云服务器订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_logs', to='cloud.cloudserverorder', verbose_name='云服务器订单'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='order_no',
            field=models.CharField(blank=True, db_comment='订单号', db_index=True, max_length=191, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='target_chat_id',
            field=models.BigIntegerField(blank=True, db_comment='目标聊天ID', db_index=True, null=True, verbose_name='目标聊天ID'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='text_preview',
            field=models.TextField(blank=True, db_comment='通知预览', null=True, verbose_name='通知预览'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_notice_logs', to='bot.telegramuser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='account_key',
            field=models.CharField(blank=True, db_comment='账户标识', db_index=True, max_length=191, null=True, verbose_name='账户标识'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='account_scope',
            field=models.CharField(choices=[('platform', '平台账户'), ('user', '用户账户'), ('cloud', '云账户')], db_comment='账户归属类型', db_index=True, default='platform', max_length=32, verbose_name='账户归属类型'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='address',
            field=models.CharField(db_comment='地址', db_index=True, max_length=191, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='currency',
            field=models.CharField(db_comment='币种', db_index=True, max_length=32, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='expense',
            field=models.DecimalField(db_comment='支出', decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='支出'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='income',
            field=models.DecimalField(db_comment='收入', decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='收入'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='monitor',
            field=models.ForeignKey(blank=True, db_comment='监控地址', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_stats', to='cloud.addressmonitor', verbose_name='监控地址'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='stats_date',
            field=models.DateField(db_comment='统计日期', db_index=True, verbose_name='统计日期'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='user',
            field=models.ForeignKey(db_comment='用户', on_delete=django.db.models.deletion.CASCADE, related_name='daily_address_stats', to='bot.telegramuser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='account_key',
            field=models.CharField(blank=True, db_comment='账户标识', db_index=True, max_length=191, null=True, verbose_name='账户标识'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='account_scope',
            field=models.CharField(choices=[('platform', '平台账户'), ('user', '用户账户'), ('cloud', '云账户')], db_comment='账户归属类型', db_index=True, default='platform', max_length=32, verbose_name='账户归属类型'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='address',
            field=models.CharField(db_comment='地址', db_index=True, max_length=191, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='bandwidth',
            field=models.BigIntegerField(db_comment='可用带宽', default=0, verbose_name='可用带宽'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='captured_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='采集时间', db_index=True, verbose_name='采集时间'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='delta_bandwidth',
            field=models.BigIntegerField(db_comment='带宽变化', default=0, verbose_name='带宽变化'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='delta_energy',
            field=models.BigIntegerField(db_comment='能量变化', default=0, verbose_name='能量变化'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='energy',
            field=models.BigIntegerField(db_comment='可用能量', default=0, verbose_name='可用能量'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='monitor',
            field=models.ForeignKey(db_comment='监控地址', on_delete=django.db.models.deletion.CASCADE, related_name='resource_snapshots', to='cloud.addressmonitor', verbose_name='监控地址'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='bandwidth',
            field=models.CharField(blank=True, db_comment='带宽', max_length=64, null=True, verbose_name='带宽'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='bundle_code',
            field=models.CharField(db_comment='规格代码', db_index=True, max_length=128, verbose_name='规格代码'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='config_id',
            field=models.CharField(blank=True, db_comment='配置ID', db_index=True, default='', max_length=64, verbose_name='配置ID'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='cost_price',
            field=models.DecimalField(db_comment='进货价', decimal_places=6, default=0, max_digits=18, verbose_name='进货价'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='cpu',
            field=models.CharField(blank=True, db_comment='CPU', max_length=64, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='currency',
            field=models.CharField(db_comment='币种', default='USDT', max_length=32, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='display_bandwidth',
            field=models.CharField(blank=True, db_comment='展示带宽', max_length=64, verbose_name='展示带宽'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='display_cpu',
            field=models.CharField(blank=True, db_comment='展示CPU', max_length=64, verbose_name='展示CPU'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='display_description',
            field=models.TextField(blank=True, db_comment='展示说明', verbose_name='展示说明'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='display_memory',
            field=models.CharField(blank=True, db_comment='展示内存', max_length=64, verbose_name='展示内存'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='display_plan_name',
            field=models.CharField(blank=True, db_comment='展示套餐名', max_length=191, verbose_name='展示套餐名'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='display_storage',
            field=models.CharField(blank=True, db_comment='展示存储', max_length=64, verbose_name='展示存储'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='is_active',
            field=models.BooleanField(db_comment='启用', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='memory',
            field=models.CharField(blank=True, db_comment='内存', max_length=64, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='price',
            field=models.DecimalField(db_comment='销售价格', decimal_places=6, max_digits=18, verbose_name='销售价格'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='provider',
            field=models.CharField(choices=[('aws_lightsail', 'AWS 光帆服务器'), ('aliyun_simple', '阿里云轻量云')], db_comment='云厂商', db_index=True, max_length=32, verbose_name='云厂商'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='region_code',
            field=models.CharField(db_comment='地区代码', db_index=True, max_length=64, verbose_name='地区代码'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='region_name',
            field=models.CharField(db_comment='地区名称', max_length=128, verbose_name='地区名称'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='server_description',
            field=models.TextField(blank=True, db_comment='服务器价格描述', null=True, verbose_name='服务器价格描述'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='server_name',
            field=models.CharField(db_comment='服务器价格名', max_length=191, verbose_name='服务器价格名'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='sort_order',
            field=models.IntegerField(db_comment='排序', default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='storage',
            field=models.CharField(blank=True, db_comment='存储', max_length=64, null=True, verbose_name='存储'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
    ]
