# Generated by Django 5.2.13 on 2026-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0050_alter_addressmonitor_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmonitor',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudasset',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudassetdashboardsnapshot',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjob',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudassetsyncjobevent',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewpatrollog',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudautorenewretrytask',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudiplog',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycleplannote',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudlifecycletask',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudnoticetask',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudserverorder',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudserverplan',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudusernoticelog',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailyaddressstat',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resourcesnapshot',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serverprice',
            name='id',
            field=models.BigAutoField(db_comment='主键ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
