# Generated by Codex on 2026-06-06

from django.db import migrations, models


def backfill_asset_due_sort_at(apps, schema_editor):
    table = schema_editor.quote_name('cloud_asset_dashboard_snapshot')
    asset_table = schema_editor.quote_name('cloud_asset')
    column = schema_editor.quote_name('asset_due_sort_at')
    asset_id = schema_editor.quote_name('asset_id')
    actual_expires_at = schema_editor.quote_name('actual_expires_at')
    id_column = schema_editor.quote_name('id')
    if schema_editor.connection.vendor == 'mysql':
        schema_editor.execute(
            f'UPDATE {table} snapshot '
            f'JOIN {asset_table} asset ON snapshot.{asset_id} = asset.{id_column} '
            f'SET snapshot.{column} = asset.{actual_expires_at}'
        )
        return
    schema_editor.execute(
        f'UPDATE {table} '
        f'SET {column} = ('
        f'SELECT asset.{actual_expires_at} FROM {asset_table} asset '
        f'WHERE asset.{id_column} = {table}.{asset_id}'
        f')'
    )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('cloud', '0051_alter_addressmonitor_id_alter_cloudasset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudassetdashboardsnapshot',
            name='asset_due_sort_at',
            field=models.DateTimeField(blank=True, db_comment='仅用于后台列表排序缓存，来源 CloudAsset.actual_expires_at，不作为资产到期事实', db_index=True, null=True, verbose_name='资产到期排序缓存'),
        ),
        migrations.RunPython(backfill_asset_due_sort_at, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['group_user_key', 'asset_due_sort_at', 'group_user_label'], name='cad_user_due_page_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['group_telegram_key', 'asset_due_sort_at', 'group_telegram_label'], name='cad_tg_due_page_idx'),
        ),
    ]
