# Generated by Codex on 2026-06-06

from django.db import migrations, models


def backfill_is_display_visible(apps, schema_editor):
    table = schema_editor.quote_name('cloud_asset_dashboard_snapshot')
    column = schema_editor.quote_name('is_display_visible')
    risk_unattached_ip = schema_editor.quote_name('risk_unattached_ip')
    is_active = schema_editor.quote_name('is_active')
    status = schema_editor.quote_name('status')
    hidden_statuses = "'deleted', 'deleting', 'expired', 'terminated', 'terminating', 'unknown'"
    schema_editor.execute(
        f'UPDATE {table} '
        f'SET {column} = CASE '
        f'WHEN {risk_unattached_ip} OR ({is_active} AND ({status} IS NULL OR {status} NOT IN ({hidden_statuses}))) '
        f'THEN 1 ELSE 0 END'
    )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('cloud', '0052_cloud_asset_dashboard_snapshot_due_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudassetdashboardsnapshot',
            name='is_display_visible',
            field=models.BooleanField(db_comment='后台列表 show_deleted=0 时的可见性缓存', db_index=True, default=True, verbose_name='后台列表可显示'),
        ),
        migrations.RunPython(backfill_is_display_visible, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['is_display_visible', 'group_user_key', 'asset_due_sort_at', 'group_user_label'], name='cad_vis_user_due_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['is_display_visible', 'group_telegram_key', 'asset_due_sort_at', 'group_telegram_label'], name='cad_vis_tg_due_idx'),
        ),
    ]
