# Generated by Django 5.2.13 on 2026-06-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_adminreplylink_id_alter_botoperationlog_id_and_more'),
        ('cloud', '0055_cloudasset_kind_updated_index'),
        ('core', '0015_comment_django_system_tables'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cloudasset',
            index=models.Index(fields=['kind', '-sort_order', 'actual_expires_at', '-updated_at'], name='ca_kind_sort_due_idx'),
        ),
    ]
