# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0056_cloudasset_lifecycle_plan_sort_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cloudasset',
            index=models.Index(fields=['kind', 'is_active', 'actual_expires_at', 'id'], name='ca_lifecycle_page_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudasset',
            index=models.Index(fields=['kind', 'actual_expires_at', 'id'], name='ca_lifecycle_any_page_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudiplog',
            index=models.Index(fields=['event_type', '-id'], name='cil_event_id_desc_idx'),
        ),
    ]
