# Generated by Django 5.2.13 on 2026-06-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0059_dashboard_snapshot_group_due_order_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_normal', 'risk_account_disabled', 'group_user_key'], name='cad_norm_user_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_normal', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_norm_user_due_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_account_disabled', 'group_user_key'], name='cad_acct_user_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_acct_user_due_ord_idx'),
        ),
    ]
