# Generated by Django 5.2.13 on 2026-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_adminreplylink_id_alter_botoperationlog_id_and_more'),
        ('cloud', '0060_dashboard_snapshot_risk_group_indexes'),
        ('core', '0015_comment_django_system_tables'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_normal', 'risk_account_disabled', 'group_telegram_key'], name='cad_norm_tg_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_due_soon', 'risk_account_disabled', 'group_telegram_key'], name='cad_due_tg_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_expired', 'risk_account_disabled', 'group_telegram_key'], name='cad_exp_tg_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_unattached_ip', 'risk_account_disabled', 'group_telegram_key'], name='cad_unatt_tg_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_abnormal', 'risk_account_disabled', 'group_telegram_key'], name='cad_abn_tg_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_account_disabled', 'group_telegram_key'], name='cad_acct_tg_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_shutdown_disabled', 'risk_account_disabled', 'group_telegram_key'], name='cad_shut_tg_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_unbound_user', 'risk_account_disabled', 'group_telegram_key'], name='cad_nouser_tg_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_unbound_group', 'risk_account_disabled', 'group_telegram_key'], name='cad_nogroup_tg_group_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_auto_renew_off', 'risk_account_disabled', 'group_telegram_key'], name='cad_renewoff_tg_group_idx'),
        ),
    ]
