# Generated by Django 5.2.13 on 2026-06-07 21:26

from django.db import migrations, models


def _index_definitions():
    return [
        models.Index(fields=['risk_due_soon', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_due_user_due_ord_idx'),
        models.Index(fields=['risk_expired', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_exp_user_due_ord_idx'),
        models.Index(fields=['risk_unattached_ip', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_unatt_user_due_ord_idx'),
        models.Index(fields=['risk_abnormal', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_abn_user_due_ord_idx'),
        models.Index(fields=['risk_unbound_user', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_nouser_user_due_idx'),
        models.Index(fields=['risk_unbound_group', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_nogroup_user_due_idx'),
    ]


def _existing_index_names(connection, table_name):
    with connection.cursor() as cursor:
        return set(connection.introspection.get_constraints(cursor, table_name).keys())


def create_missing_indexes(apps, schema_editor):
    model = apps.get_model('cloud', 'CloudAssetDashboardSnapshot')
    existing = _existing_index_names(schema_editor.connection, model._meta.db_table)
    for index in _index_definitions():
        if index.name in existing:
            continue
        schema_editor.add_index(model, index)
        existing.add(index.name)


def drop_user_risk_due_indexes(apps, schema_editor):
    model = apps.get_model('cloud', 'CloudAssetDashboardSnapshot')
    existing = _existing_index_names(schema_editor.connection, model._meta.db_table)
    for index in reversed(_index_definitions()):
        if index.name not in existing:
            continue
        schema_editor.remove_index(model, index)
        existing.remove(index.name)


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_adminreplylink_id_alter_botoperationlog_id_and_more'),
        ('cloud', '0061_dashboard_snapshot_tg_risk_group_indexes'),
        ('core', '0015_comment_django_system_tables'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_missing_indexes, drop_user_risk_due_indexes),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='cloudassetdashboardsnapshot',
                    index=models.Index(fields=['risk_due_soon', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_due_user_due_ord_idx'),
                ),
                migrations.AddIndex(
                    model_name='cloudassetdashboardsnapshot',
                    index=models.Index(fields=['risk_expired', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_exp_user_due_ord_idx'),
                ),
                migrations.AddIndex(
                    model_name='cloudassetdashboardsnapshot',
                    index=models.Index(fields=['risk_unattached_ip', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_unatt_user_due_ord_idx'),
                ),
                migrations.AddIndex(
                    model_name='cloudassetdashboardsnapshot',
                    index=models.Index(fields=['risk_abnormal', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_abn_user_due_ord_idx'),
                ),
                migrations.AddIndex(
                    model_name='cloudassetdashboardsnapshot',
                    index=models.Index(fields=['risk_unbound_user', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_nouser_user_due_idx'),
                ),
                migrations.AddIndex(
                    model_name='cloudassetdashboardsnapshot',
                    index=models.Index(fields=['risk_unbound_group', 'risk_account_disabled', 'asset_due_sort_null_rank', 'asset_due_sort_at', 'group_user_label', 'group_user_key'], name='cad_nogroup_user_due_idx'),
                ),
            ],
        ),
    ]
