# Generated by Django 5.2.13 on 2026-06-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_adminreplylink_id_alter_botoperationlog_id_and_more'),
        ('cloud', '0062_dashboard_snapshot_user_risk_due_indexes'),
        ('core', '0015_comment_django_system_tables'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cloudassetdashboardsnapshot',
            name='cad_risk_display_idx',
        ),
        migrations.AddIndex(
            model_name='cloudassetdashboardsnapshot',
            index=models.Index(fields=['risk_account_disabled', 'risk_rank', 'asset_due_sort_null_rank', 'asset_due_sort_at', '-sort_order', '-asset_id'], name='cad_acct_list_page_idx'),
        ),
    ]
