# Generated by Django 5.2.13 on 2026-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0063_account_disabled_snapshot_page_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudasset',
            name='shutdown_enabled',
            field=models.BooleanField(db_comment='关机计划启用', db_index=True, default=False, verbose_name='关机计划启用'),
        ),
    ]
